export type ApprovedStudioImage={id:string;name:string;dataUrl:string;mimeType:string;width?:number;height?:number;source:"transparent-product"|"background-studio"|"product-preview"|"import";approvedAt:string};
export type DekoBrainMarketingContext={productDNA?:Record<string,unknown>;echoScore?:number;category?:string;confidence?:number;dekoBrainResults?:Record<string,unknown>};
export type MarketingContent={productTitle:string;shortDescription:string;longDescription:string;adText:string;facebookPost:string;instagramPost:string;seoKeywords:string[];hashtags:string[];generatedAt:string};
const APPROVED_IMAGE_KEY="dekokraft:eco-studio:approved-image",MARKETING_CONTEXT_KEY="dekokraft:eco-studio:marketing-context",MARKETING_CONTENT_KEY="dekokraft:eco-studio:marketing-content",EVENT="eco-studio-state-change";
function available(){return typeof window!=="undefined"}function read<T>(key:string,valid:(value:unknown)=>value is T):T|null{if(!available())return null;try{const raw=localStorage.getItem(key);if(!raw)return null;const value:unknown=JSON.parse(raw);return valid(value)?value:null}catch{return null}}function write(key:string,value:unknown){if(!available())return;try{localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new CustomEvent(EVENT))}catch{window.dispatchEvent(new CustomEvent(EVENT,{detail:{error:"storage-failed"}}))}}function remove(key:string){if(!available())return;localStorage.removeItem(key);window.dispatchEvent(new CustomEvent(EVENT))}function object(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==="object"&&!Array.isArray(value)}
export function saveApprovedStudioImage(image:ApprovedStudioImage){write(APPROVED_IMAGE_KEY,image)}export function getApprovedStudioImage(){return read(APPROVED_IMAGE_KEY,(value):value is ApprovedStudioImage=>object(value)&&typeof value.id==="string"&&typeof value.name==="string"&&typeof value.dataUrl==="string"&&typeof value.mimeType==="string"&&typeof value.source==="string"&&typeof value.approvedAt==="string")}export function removeApprovedStudioImage(){remove(APPROVED_IMAGE_KEY)}
export function saveMarketingContext(context:DekoBrainMarketingContext){write(MARKETING_CONTEXT_KEY,context)}export function getMarketingContext(){return read(MARKETING_CONTEXT_KEY,(value):value is DekoBrainMarketingContext=>object(value))}
export function saveMarketingContent(content:MarketingContent){write(MARKETING_CONTENT_KEY,content)}export function getMarketingContent(){return read(MARKETING_CONTENT_KEY,(value):value is MarketingContent=>object(value)&&typeof value.productTitle==="string"&&Array.isArray(value.seoKeywords)&&Array.isArray(value.hashtags))}export function removeMarketingContent(){remove(MARKETING_CONTENT_KEY)}
export const ecoStudioStateChangeEvent=EVENT;
export function blobToDataUrl(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>typeof reader.result==="string"?resolve(reader.result):reject(new Error("invalid-data-url"));reader.onerror=()=>reject(reader.error??new Error("file-read-failed"));reader.readAsDataURL(blob)})}
