"use client";
import { useEffect, useRef, useState } from "react";
import type { BackgroundStudioCopy } from "../../config/dekoBrainBackgroundStudioTranslations";
import type { Lang } from "../../config/translations";
import { dekoBrainCanvaTranslations } from "../../config/dekoBrainCanvaTranslations";
import { composeProductBackground } from "../../lib/dekobrain/composeBackground";
import type { AnalyzedMediaItem, BackgroundStudioType, DekoBrainCompositionSettings } from "../../types/dekobrain";
import CanvaDesignAssistant from "./CanvaDesignAssistant";

const types:BackgroundStudioType[]=["transparent","white","color","gradient","blur","upload","smart"];
const defaults:DekoBrainCompositionSettings={scale:1,offsetX:0,offsetY:0,shadow:18,safeArea:6,color:"#f3eadb",gradientStart:"#f7d78a",gradientEnd:"#d99a3d"};

export default function DekoBrainBackgroundStudio({copy,item,locale,approvedAssetUrl,canUseApprovedAsset,onApprove,onBack,onCanvaExport}:{copy:BackgroundStudioCopy;item:AnalyzedMediaItem;locale:Lang;approvedAssetUrl:string;canUseApprovedAsset:boolean;onApprove:(result:{blob:Blob;url:string;backgroundType:BackgroundStudioType;settings:DekoBrainCompositionSettings})=>void;onBack:()=>void;onCanvaExport?:()=>void}){
 const transparent=item.imageState.transparentProduct;
 const [type,setType]=useState<BackgroundStudioType>(item.imageState.composedImage?.backgroundType??"transparent");
 const [settings,setSettings]=useState<DekoBrainCompositionSettings>(item.imageState.composedImage?.settings??defaults);
 const [previewUrl,setPreviewUrl]=useState(item.imageState.composedImage?.url??""); const [blob,setBlob]=useState<Blob|null>(item.imageState.composedImage?.blob??null);
 const [uploadedUrl,setUploadedUrl]=useState(""); const [status,setStatus]=useState(""); const [compare,setCompare]=useState(false);const [surface,setSurface]=useState<"checkerboard"|"light"|"dark">("checkerboard");const [smartMessage,setSmartMessage]=useState("");const [prompt,setPrompt]=useState("");
 const [canvaOpenRequest,setCanvaOpenRequest]=useState(0);const canvaCopy=dekoBrainCanvaTranslations[locale];
 const generated=useRef("");const uploaded=useRef("");
 useEffect(()=>()=>{if(generated.current)URL.revokeObjectURL(generated.current);if(uploaded.current)URL.revokeObjectURL(uploaded.current);},[]);
 useEffect(()=>{
  if(!transparent?.approved)return;let cancelled=false;const timer=window.setTimeout(async()=>{setStatus(copy.processing);try{const nextBlob=await composeProductBackground({productUrl:transparent.url,originalUrl:item.imageState.originalImage?.url??item.previewUrl,backgroundType:type,settings,uploadedBackgroundUrl:uploadedUrl});if(cancelled)return;const url=URL.createObjectURL(nextBlob);if(generated.current)URL.revokeObjectURL(generated.current);generated.current=url;setPreviewUrl(url);setBlob(nextBlob);setStatus("");}catch{if(!cancelled)setStatus(copy.error);}},250);return()=>{cancelled=true;window.clearTimeout(timer);};
 },[transparent,type,settings,uploadedUrl,item.imageState.originalImage?.url,item.previewUrl,copy.processing,copy.error]);
 const update=(patch:Partial<DekoBrainCompositionSettings>)=>setSettings(current=>({...current,...patch}));
 function uploadBackground(file:File){if(uploaded.current)URL.revokeObjectURL(uploaded.current);const url=URL.createObjectURL(file);uploaded.current=url;setUploadedUrl(url);setType("upload");}
 function approve(){if(!blob||!previewUrl)return;onApprove({blob,url:previewUrl,backgroundType:type,settings});generated.current="";}
 if(!transparent?.approved)return <section className="dkBrainPanel dkBrainStudioPanel" id="dkbrain-background-studio"><div className="dkBrainSectionHeading"><div><span>08</span><h2>{copy.title}</h2></div></div><p>{copy.locked}</p><button type="button" onClick={onBack}>{copy.back}</button><CanvaDesignAssistant locale={locale} sourceIdentity={item.id} sourceUrl={item.imageState.originalImage?.url??null} sourceFileName={item.filename} sourceMimeType={item.mimeType} width={item.width} height={item.height} isBackgroundApproved={false} backgroundMode="transparent"/></section>;
 return <section className="dkBrainPanel dkBrainStudioPanel" id="dkbrain-background-studio"><div className="dkBrainSectionHeading"><div><span>08</span><h2>{copy.title}</h2></div></div><p>{copy.description}</p>
  <div className="dkBrainStudioTypes">{types.map(value=><button type="button" key={value} className={type===value?"active":""} onClick={()=>setType(value)}>{copy.types[value]}</button>)}</div>
  {type==="color"&&<label>{copy.customColor}<input type="color" value={settings.color} onChange={e=>update({color:e.target.value})}/></label>}
  {type==="gradient"&&<div className="dkBrainStudioColors"><label>{copy.gradientStart}<input type="color" value={settings.gradientStart} onChange={e=>update({gradientStart:e.target.value})}/></label><label>{copy.gradientEnd}<input type="color" value={settings.gradientEnd} onChange={e=>update({gradientEnd:e.target.value})}/></label></div>}
  {type==="upload"&&<label className="dkBrainStudioUpload">{copy.uploadBackground}<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&uploadBackground(e.target.files[0])}/></label>}
  {type==="smart"&&<div className="dkBrainSmartPlaceholder"><label>{copy.smartPrompt}<input value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><label>{copy.style}<select>{copy.styles.map(style=><option key={style}>{style}</option>)}</select></label><button type="button" onClick={()=>setSmartMessage(copy.future)}>{copy.generate}</button>{smartMessage&&<p role="status">{smartMessage}</p>}</div>}
  <div className="dkBrainStudioControls">{([["scale",.4,1.4,.01],["offsetX",-100,100,1],["offsetY",-100,100,1],["shadow",0,80,1],["safeArea",0,25,1]] as const).map(([key,min,max,step])=><label key={key}>{copy[key]}: <b>{settings[key]}</b><input type="range" min={min} max={max} step={step} value={settings[key]} onChange={e=>update({[key]:Number(e.target.value)})}/></label>)}</div>
  <h3>{copy.finalPreview}</h3><div className={`dkBrainStudioPreview ${surface} ${compare?"compare":""}`}>{compare&&<img src={item.imageState.originalImage?.url??item.previewUrl} alt={item.filename}/>}<img src={previewUrl||transparent.url} alt={item.filename}/></div>{status&&<p role="status">{status}</p>}
  <div className="dkBrainStudioPreviewActions"><button type="button" className={compare?"active":""} onClick={()=>setCompare(v=>!v)}>{copy.compare}</button><button type="button" className={surface==="checkerboard"?"active":""} onClick={()=>setSurface("checkerboard")}>{copy.checkerboard}</button><button type="button" className={surface==="light"?"active":""} onClick={()=>setSurface("light")}>{copy.light}</button><button type="button" className={surface==="dark"?"active":""} onClick={()=>setSurface("dark")}>{copy.dark}</button></div>
  <div className="dkBrainStudioFinalActions"><button type="button" className="primary" disabled={!blob} onClick={approve}>{item.imageState.composedImage?.approved?copy.approved:copy.approve}</button><button type="button" onClick={onBack}>{copy.back}</button><button type="button" disabled={!canUseApprovedAsset} title={!canUseApprovedAsset?copy.locked:undefined} onClick={()=>document.getElementById("dkbrain-webp-conversion")?.scrollIntoView({behavior:"smooth",block:"center"})}>{copy.webp}</button><button type="button" disabled={!canUseApprovedAsset} title={!canUseApprovedAsset?copy.locked:undefined} onClick={()=>setSmartMessage(copy.futureAction)}>{copy.gallery}</button><button type="button" disabled={!canUseApprovedAsset} title={!canUseApprovedAsset?copy.locked:undefined} onClick={()=>setSmartMessage(copy.futureAction)}>{copy.product}</button><button type="button" className="dkBrainCanvaAction" disabled={!canUseApprovedAsset} title={!canUseApprovedAsset?copy.locked:undefined} onClick={()=>setCanvaOpenRequest(value=>value+1)}>{canvaCopy.designButton}</button></div>{smartMessage&&type!=="smart"&&<p role="status">{smartMessage}</p>}
  <CanvaDesignAssistant hideTrigger openRequest={canvaOpenRequest} onExportRequested={onCanvaExport} locale={locale} sourceIdentity={item.id} sourceUrl={canUseApprovedAsset?approvedAssetUrl:null} sourceFileName={`${item.filename.replace(/\.[^.]+$/,"")}-${item.imageState.composedImage?.approved?"composed":"transparent"}.png`} sourceMimeType={item.imageState.composedImage?.approved?item.imageState.composedImage.blob.type:item.imageState.transparentProduct?.blob.type} width={item.width} height={item.height} isBackgroundApproved={canUseApprovedAsset} backgroundMode={item.imageState.composedImage?.approved?(item.imageState.composedImage.backgroundType==="transparent"?"transparent":item.imageState.composedImage.backgroundType==="white"?"white":item.imageState.composedImage.backgroundType==="smart"?"generated":"custom"):"transparent"}/>
 </section>;
}
