import type { Lang } from "./translations";
import type {
  AdvisorImprovement,
  AdvisorReason,
  AdvisorStrength,
  AdvisorUse,
  AdvisorVerdict,
  BackgroundMode,
  CompatibilityOverride,
  CompatibilityStatus,
  ProvisionalCategory,
} from "../types/dekobrain";

export interface DekoBrainAdvisorCopy {
  contentTitle: string;
  provisionalBadge: string;
  provisionalExplanation: string;
  categoryLabel: string;
  categorySource: string;
  categorySources: Record<"user" | "local-heuristic" | "future-ai", string>;
  categories: Record<ProvisionalCategory, string>;
  confirmCategory: string;
  confirmed: string;
  gypsumDescription?: string;
  compatibilityTitle: string;
  compatibility: Record<CompatibilityStatus, string>;
  compatibilityReasons: Record<CompatibilityStatus, string>;
  overrideLabel: string;
  overrides: Record<CompatibilityOverride, string>;
  backgroundTitle: string;
  backgroundExtractionDescription: string;
  originalImageLabel: string;
  transparentPreviewLabel: string;
  backgroundModes: Record<BackgroundMode, string>;
  backgroundHelp: Record<BackgroundMode, string>;
  comingSoon: string;
  transparentReal: string;
  backgroundProcessing: string;
  transparentReady: string;
  backgroundTolerance: string;
  edgeSoftness: string;
  productDetailProtection: string;
  previewBackground: string;
  previewCheckerboard: string;
  previewDark: string;
  previewLight: string;
  compareBeforeAfter: string;
  approveTransparent: string;
  transparentApproved: string;
  backgroundComplex: string;
  backgroundHeuristicNotice: string;
  backgroundError: string;
  shadowMode: string;
  shadowKeep: string;
  shadowSoften: string;
  shadowRemoveExperimental: string;
  shadowExperimentalWarning: string;
  highSensitivityWarning: string;
  unsafeSensitivityWarning: string;
  extractionUnapproved: string;
  extractionApproved: string;
  naturalShadowAdvice: string;
  conversionTitle: string;
  quality: string;
  convert: string;
  converting: string;
  download: string;
  useConverted: string;
  conversionError: string;
  gifWarning: string;
  originalFormat: string;
  outputFormat: string;
  originalSize: string;
  convertedSize: string;
  saved: string;
  outputDimensions: string;
  noConversion: string;
  advisorTitle: string;
  advisorSubtitle: string;
  verdicts: Record<AdvisorVerdict, string>;
  readinessScore: string;
  why: string;
  strengthsTitle: string;
  improvementsTitle: string;
  usesTitle: string;
  reasons: Record<AdvisorReason, string>;
  strengths: Record<AdvisorStrength, string>;
  improvements: Record<AdvisorImprovement, string>;
  uses: Record<AdvisorUse, string>;
  useAsIs: string;
  advisorDisclaimer: string;
  stagePartial: string;
  stageDetails: { contentPartial: string; compatibilityReady: string; backgroundPartial: string; conversionReady: string; advisorReady: string };
}

export const dekoBrainAdvisorTranslations: Record<Lang, DekoBrainAdvisorCopy> = {
  ar: {
    contentTitle: "تحليل محتوى الصورة", provisionalBadge: "تحليل محلي مبدئي", provisionalExplanation: "يعتمد التصنيف المبدئي على اسم الملف واختيار المستخدم فقط. سيتم ربط رؤية حاسوبية حقيقية لاحقًا.", categoryLabel: "فئة المنتج المبدئية", categorySource: "مصدر التصنيف", categorySources: { user: "اختيار المستخدم", "local-heuristic": "قاعدة محلية", "future-ai": "رؤية ذكية مستقبلية" },
    categories: { candles: "شموع", packaging: "تعليب وتغليف", gifts: "هدايا", children: "أطفال وتعليم", decoration: "ديكور", services: "خدمات", "gypsum-decor": "ديكور من الجبس", other: "أخرى" }, confirmCategory: "تأكيد الفئة", confirmed: "تم التأكيد", gypsumDescription: "منتج ديكوري مصنوع أساسًا من الجبس، وقد يحتوي على زخارف بارزة وحواف دقيقة وأجزاء قابلة للكسر.",
    compatibilityTitle: "التوافق مع نشاط المنصة", compatibility: { compatible: "متوافق", needsReview: "يحتاج مراجعة", incompatible: "غير متوافق", unknown: "غير معروف" }, compatibilityReasons: { compatible: "الفئة ضمن الأنشطة المدعومة حاليًا في DekoKraft.", needsReview: "الفئة «أخرى» تحتاج قرارًا بشريًا قبل الاستخدام.", incompatible: "تم رفض التوافق يدويًا من المسؤول.", unknown: "لا توجد معلومات كافية لاتخاذ قرار." }, overrideLabel: "قرار المسؤول", overrides: { none: "بدون تجاوز", approved: "اعتماد التوافق", rejected: "رفض التوافق" },
    backgroundTitle: "استخراج المنتج الشفاف", backgroundExtractionDescription: "اعزل المنتج عن الخلفية، اضبط الحواف، ثم اعتمد النسخة الشفافة قبل الانتقال إلى استوديو الخلفيات.", originalImageLabel: "الصورة الأصلية", transparentPreviewLabel: "المعاينة الشفافة", backgroundModes: { original: "الاحتفاظ بالأصل", white: "خلفية بيضاء", transparent: "خلفية شفافة", blur: "تمويه الخلفية", remove: "إزالة الخلفية" }, backgroundHelp: { original: "يعرض الصورة الأصلية دون معالجة.", white: "يعرض الصورة فوق إطار أبيض.", transparent: "يفصل الخلفيات البسيطة محليًا ويعرض الشفافية الحقيقية.", blur: "يعرض نسخة مموهة خلف الصورة الأصلية.", remove: "تحتاج إزالة الخلفية إلى مزود ذكي في مرحلة لاحقة." }, comingSoon: "قريبًا",
    transparentReal: "خلفية شفافة حقيقية", backgroundProcessing: "جارٍ فصل المنتج عن الخلفية…", transparentReady: "المعاينة الشفافة جاهزة", backgroundTolerance: "حساسية اكتشاف الخلفية", edgeSoftness: "نعومة الحواف", productDetailProtection: "حماية تفاصيل المنتج", previewBackground: "خلفية المعاينة", previewCheckerboard: "شبكة الشفافية", previewDark: "معاينة داكنة", previewLight: "معاينة فاتحة", compareBeforeAfter: "مقارنة قبل وبعد", approveTransparent: "اعتماد المنتج الشفاف", transparentApproved: "تم اعتماد المنتج الشفاف", backgroundComplex: "الخلفية معقدة وتحتاج إلى إزالة بالذكاء الاصطناعي", backgroundHeuristicNotice: "هذه معالجة محلية مبدئية للخلفيات البسيطة", backgroundError: "تعذرت معالجة الخلفية محليًا.", shadowMode: "معالجة الظل", shadowKeep: "الاحتفاظ بالظل", shadowSoften: "تخفيف الظل", shadowRemoveExperimental: "إزالة الظل تجريبيًا", shadowExperimentalWarning: "إزالة الظل تجريبية. تم حذف طبقة الظل فقط دون تعديل جسم المنتج.", highSensitivityWarning: "حساسية مرتفعة قد تحذف أجزاء من المنتج.", unsafeSensitivityWarning: "الحساسية مرتفعة جدًا وقد تحذف أجزاء من المنتج. اخفضها إلى 85 أو أقل قبل الاعتماد.", extractionUnapproved: "معاينة غير معتمدة", extractionApproved: "تم اعتماد المنتج الشفاف", naturalShadowAdvice: "الاحتفاظ بظل طبيعي أفضل من حذف أجزاء من المنتج.",
    conversionTitle: "التحويل والضغط إلى WebP", quality: "جودة WebP", convert: "تحويل إلى WebP", converting: "جارٍ التحويل…", download: "تنزيل WebP", useConverted: "استخدام الملف المحوّل", conversionError: "تعذر تحويل الملف إلى WebP.", gifWarning: "لا يتم تحويل GIF المتحرك تلقائيًا حتى لا تضيع الحركة.", originalFormat: "الصيغة الأصلية", outputFormat: "صيغة الإخراج", originalSize: "الحجم الأصلي", convertedSize: "الحجم بعد التحويل", saved: "نسبة التوفير", outputDimensions: "أبعاد الإخراج", noConversion: "لم يتم إنشاء ملف WebP بعد.",
    advisorTitle: "رأي DekoBrain", advisorSubtitle: "قرار تقني محلي قابل للتفسير من محرك القرار، وليس حكمًا على الجمال أو النجاح التجاري.", verdicts: { ready: "جاهز", readyWithImprovements: "جاهز مع تحسينات", reviewRequired: "يحتاج مراجعة", notReady: "غير جاهز" }, readinessScore: "درجة الجاهزية التقنية", why: "لماذا صدر هذا القرار؟", strengthsTitle: "نقاط القوة", improvementsTitle: "التحسينات المقترحة", usesTitle: "أماكن الاستخدام المقترحة",
    reasons: { technicalStrong: "الجودة التقنية الأساسية قوية.", technicalAdequate: "الجودة التقنية مقبولة للاستخدام الرقمي.", technicalWeak: "المؤشرات التقنية تحتاج تحسينًا.", categoryConfirmed: "تم تأكيد الفئة من المستخدم.", categoryUnconfirmed: "الفئة المبدئية لم تُؤكد بعد.", compatible: "الفئة متوافقة مع نشاط المنصة.", compatibilityReview: "التوافق يحتاج قرارًا بشريًا.", incompatible: "تم تحديد المحتوى كغير متوافق يدويًا.", conversionAvailable: "يمكن تحسين كفاءة الملف عبر WebP.", conversionCompleted: "الملف بصيغة WebP أو تم تحويله فعليًا.", finalCompositionReady:"تم اعتماد نسخة نهائية مركبة." },
    strengths: { resolution: "دقة جيدة", fileSize: "حجم ملف مناسب", format: "صيغة ويب فعالة", cardRatio: "إطار عرض مقترح", compatibility: "توافق مؤكد", finalComposition: "نسخة نهائية جاهزة" }, improvements: { confirmCategory: "تأكيد فئة المنتج", reviewCompatibility: "مراجعة توافق الفئة", convertWebp: "التحويل إلى WebP", increaseResolution: "استخدام صورة بدقة أعلى", compressFile: "ضغط حجم الملف" }, uses: { productCard: "بطاقة منتج", gallery: "معرض الصور", hero: "صورة رئيسية عريضة", thumbnail: "صورة مصغرة", manualReview: "مراجعة داخلية فقط" }, useAsIs: "استخدام كما هي", advisorDisclaimer: "لا توجد رؤية حاسوبية أو توقعات للنقر أو المبيعات في هذه المرحلة.", stagePartial: "جزئي", stageDetails: { contentPartial: "تصنيف مبدئي محلي قابل لتأكيد المستخدم؛ الرؤية الحقيقية لاحقًا.", compatibilityReady: "فحص قواعد متوافق مع فئات DekoKraft مع تجاوز إداري.", backgroundPartial: "استخراج المنتج الشفاف يحتاج إلى اعتماد قبل الانتقال للاستوديو.", conversionReady: "تحويل WebP حقيقي محليًا عبر Canvas.", advisorReady: "محرك قرار تقني حتمي وقابل للتفسير." },
  },
  de: {
    contentTitle: "Bildinhaltsanalyse", provisionalBadge: "Lokale vorläufige Analyse", provisionalExplanation: "Die vorläufige Kategorie basiert nur auf Dateiname und Nutzerauswahl. Echte Computer Vision folgt später.", categoryLabel: "Vorläufige Produktkategorie", categorySource: "Kategoriequelle", categorySources: { user: "Nutzerauswahl", "local-heuristic": "Lokale Regel", "future-ai": "Zukünftige KI-Vision" }, categories: { candles: "Kerzen", packaging: "Verpackungen", gifts: "Geschenke", children: "Kinder und Lernen", decoration: "Dekoration", services: "Dienstleistungen", "gypsum-decor": "Gipsdekor", other: "Andere" }, confirmCategory: "Kategorie bestätigen", confirmed: "Bestätigt",
    compatibilityTitle: "Kompatibilität mit der Plattform", compatibility: { compatible: "Kompatibel", needsReview: "Prüfung nötig", incompatible: "Nicht kompatibel", unknown: "Unbekannt" }, compatibilityReasons: { compatible: "Die Kategorie gehört zu den aktuell unterstützten DekoKraft-Aktivitäten.", needsReview: "„Andere“ benötigt vor der Nutzung eine menschliche Entscheidung.", incompatible: "Die Kompatibilität wurde administrativ abgelehnt.", unknown: "Für eine Entscheidung fehlen Informationen." }, overrideLabel: "Admin-Entscheidung", overrides: { none: "Keine Übersteuerung", approved: "Kompatibilität freigeben", rejected: "Kompatibilität ablehnen" },
    backgroundTitle: "Transparentes Produkt extrahieren", backgroundExtractionDescription: "Produkt freistellen, Kanten anpassen und die transparente Version vor dem Hintergrundstudio freigeben.", originalImageLabel: "Originalbild", transparentPreviewLabel: "Transparente Vorschau", backgroundModes: { original: "Original behalten", white: "Weißer Hintergrund", transparent: "Transparenter Hintergrund", blur: "Hintergrund weichzeichnen", remove: "Hintergrund entfernen" }, backgroundHelp: { original: "Zeigt das unveränderte Original.", white: "Zeigt das Bild auf einer weißen Fläche.", transparent: "Trennt einfache Hintergründe lokal und zeigt echte Transparenz.", blur: "Zeigt eine weichgezeichnete Kopie hinter dem Original.", remove: "Hintergrundentfernung benötigt später einen echten Anbieter." }, comingSoon: "Demnächst",
    transparentReal: "Echter transparenter Hintergrund", backgroundProcessing: "Produkt wird lokal vom Hintergrund getrennt…", transparentReady: "Transparente Vorschau ist bereit", backgroundTolerance: "Hintergrundtoleranz", edgeSoftness: "Kantenweichheit", productDetailProtection: "Produktdetails schützen", previewBackground: "Vorschauhintergrund", previewCheckerboard: "Schachbrett", previewDark: "Dunkle Vorschau", previewLight: "Helle Vorschau", compareBeforeAfter: "Vorher/Nachher vergleichen", approveTransparent: "Transparentes Produkt freigeben", transparentApproved: "Transparentes Produkt freigegeben", backgroundComplex: "Der Hintergrund ist komplex. KI-Entfernung wird benötigt.", backgroundHeuristicNotice: "Dies ist eine vorläufige lokale Verarbeitung für einfache Hintergründe.", backgroundError: "Der Hintergrund konnte lokal nicht verarbeitet werden.", shadowMode: "Schattenbehandlung", shadowKeep: "Schatten behalten", shadowSoften: "Schatten abschwächen", shadowRemoveExperimental: "Schatten experimentell entfernen", shadowExperimentalWarning: "Die Schattenentfernung ist experimentell. Nur die Schattenebene wird entfernt; der Produktkörper bleibt unverändert.", highSensitivityWarning: "Hohe Empfindlichkeit kann Teile des Produkts entfernen.", unsafeSensitivityWarning: "Die Empfindlichkeit ist zu hoch und kann Produktteile entfernen. Vor der Freigabe auf 85 oder weniger reduzieren.", extractionUnapproved: "Nicht freigegebene Vorschau", extractionApproved: "Transparentes Produkt freigegeben", naturalShadowAdvice: "Ein natürlicher Schatten ist besser als entfernte Produktdetails.",
    conversionTitle: "WebP-Konvertierung und Komprimierung", quality: "WebP-Qualität", convert: "In WebP konvertieren", converting: "Konvertierung…", download: "WebP herunterladen", useConverted: "Konvertierte Datei verwenden", conversionError: "Die WebP-Konvertierung ist fehlgeschlagen.", gifWarning: "Animierte GIFs werden nicht automatisch statisch konvertiert.", originalFormat: "Originalformat", outputFormat: "Ausgabeformat", originalSize: "Originalgröße", convertedSize: "Konvertierte Größe", saved: "Einsparung", outputDimensions: "Ausgabeabmessungen", noConversion: "Noch keine WebP-Datei erzeugt.",
    advisorTitle: "DekoBrain Advisor", advisorSubtitle: "Erklärbare lokale technische Entscheidung der Decision Engine – kein Urteil über Gestaltung oder Verkaufserfolg.", verdicts: { ready: "Bereit", readyWithImprovements: "Bereit mit Verbesserungen", reviewRequired: "Prüfung erforderlich", notReady: "Nicht bereit" }, readinessScore: "Technischer Bereitschaftswert", why: "Warum diese Entscheidung?", strengthsTitle: "Stärken", improvementsTitle: "Empfohlene Verbesserungen", usesTitle: "Empfohlene Platzierungen",
    reasons: { technicalStrong: "Die technische Basisqualität ist stark.", technicalAdequate: "Die technische Qualität ist für digitale Nutzung ausreichend.", technicalWeak: "Die technischen Kennzahlen müssen verbessert werden.", categoryConfirmed: "Die Kategorie wurde bestätigt.", categoryUnconfirmed: "Die vorläufige Kategorie ist noch unbestätigt.", compatible: "Die Kategorie ist mit der Plattform kompatibel.", compatibilityReview: "Die Kompatibilität braucht eine menschliche Entscheidung.", incompatible: "Der Inhalt wurde administrativ als inkompatibel markiert.", conversionAvailable: "WebP kann die Dateieffizienz verbessern.", conversionCompleted: "Die Datei ist WebP oder wurde tatsächlich konvertiert.", finalCompositionReady: "Eine finale Komposition wurde freigegeben." }, strengths: { resolution: "Gute Auflösung", fileSize: "Geeignete Dateigröße", format: "Effizientes Webformat", cardRatio: "Passender Anzeigerahmen", compatibility: "Bestätigte Kompatibilität", finalComposition: "Finale Version bereit" }, improvements: { confirmCategory: "Produktkategorie bestätigen", reviewCompatibility: "Kompatibilität prüfen", convertWebp: "In WebP konvertieren", increaseResolution: "Bild mit höherer Auflösung verwenden", compressFile: "Datei komprimieren" }, uses: { productCard: "Produktkarte", gallery: "Bildergalerie", hero: "Breites Hauptbild", thumbnail: "Vorschaubild", manualReview: "Nur interne Prüfung" }, useAsIs: "Unverändert verwenden", advisorDisclaimer: "Keine Computer Vision, Klick- oder Umsatzprognose ist in dieser Phase verbunden.", stagePartial: "Teilweise", stageDetails: { contentPartial: "Lokale vorläufige Kategorie mit Nutzerbestätigung; echte Vision folgt.", compatibilityReady: "Regelbasiert mit administrativer Übersteuerung.", backgroundPartial: "Die transparente Produktextraktion muss vor dem Studio freigegeben werden.", conversionReady: "Echte lokale WebP-Konvertierung über Canvas.", advisorReady: "Deterministische, erklärbare technische Decision Engine." },
  },
  en: {
    contentTitle: "Image content analysis", provisionalBadge: "Local provisional analysis", provisionalExplanation: "The provisional category uses only the filename and user selection. Real computer vision will be connected later.", categoryLabel: "Provisional product category", categorySource: "Category source", categorySources: { user: "User selection", "local-heuristic": "Local heuristic", "future-ai": "Future AI vision" }, categories: { candles: "Candles", packaging: "Packaging", gifts: "Gifts", children: "Children and education", decoration: "Decoration", services: "Services", "gypsum-decor": "Gypsum Decor", other: "Other" }, confirmCategory: "Confirm category", confirmed: "Confirmed",
    compatibilityTitle: "Platform activity compatibility", compatibility: { compatible: "Compatible", needsReview: "Needs review", incompatible: "Incompatible", unknown: "Unknown" }, compatibilityReasons: { compatible: "The category is among DekoKraft’s currently supported activities.", needsReview: "Other requires a human decision before use.", incompatible: "Compatibility was manually rejected by an administrator.", unknown: "There is not enough information for a decision." }, overrideLabel: "Admin decision", overrides: { none: "No override", approved: "Approve compatibility", rejected: "Reject compatibility" },
    backgroundTitle: "Transparent product extraction", backgroundExtractionDescription: "Isolate the product, refine its edges, then approve the transparent version before entering the Background Studio.", originalImageLabel: "Original image", transparentPreviewLabel: "Transparent preview", backgroundModes: { original: "Keep original", white: "White background", transparent: "Transparent background", blur: "Blur background", remove: "Remove background" }, backgroundHelp: { original: "Shows the unchanged original.", white: "Shows the image on a white frame.", transparent: "Locally separates simple backgrounds and shows real transparency.", blur: "Shows a blurred copy behind the original.", remove: "Background removal requires a real provider in a later phase." }, comingSoon: "Coming soon",
    transparentReal: "Real transparent background", backgroundProcessing: "Processing background…", transparentReady: "Transparent preview ready", backgroundTolerance: "Background tolerance", edgeSoftness: "Edge softness", productDetailProtection: "Protect product details", previewBackground: "Preview background", previewCheckerboard: "Checkerboard", previewDark: "Dark preview", previewLight: "Light preview", compareBeforeAfter: "Compare before and after", approveTransparent: "Approve transparent product", transparentApproved: "Transparent product approved", backgroundComplex: "The background is complex. Use AI background removal when the vision service is connected.", backgroundHeuristicNotice: "This is preliminary local processing for simple backgrounds.", backgroundError: "The background could not be processed locally.", shadowMode: "Shadow treatment", shadowKeep: "Keep shadow", shadowSoften: "Soften shadow", shadowRemoveExperimental: "Remove shadow experimentally", shadowExperimentalWarning: "Shadow removal is experimental. Only the shadow layer is removed; the product body is unchanged.", highSensitivityWarning: "High sensitivity may remove parts of the product.", unsafeSensitivityWarning: "Sensitivity is too high and may remove parts of the product. Reduce it to 85 or lower before approval.", extractionUnapproved: "Unapproved preview", extractionApproved: "Transparent product approved", naturalShadowAdvice: "Keeping a natural shadow is better than removing product details.",
    conversionTitle: "WebP conversion and compression", quality: "WebP quality", convert: "Convert to WebP", converting: "Converting…", download: "Download WebP", useConverted: "Use converted file", conversionError: "The file could not be converted to WebP.", gifWarning: "Animated GIF is not converted to a static image automatically.", originalFormat: "Original format", outputFormat: "Output format", originalSize: "Original size", convertedSize: "Converted size", saved: "Percentage saved", outputDimensions: "Output dimensions", noConversion: "No WebP file has been generated yet.",
    advisorTitle: "DekoBrain Advisor", advisorSubtitle: "An explainable local technical decision from the Decision Engine, not a judgment of beauty or commercial success.", verdicts: { ready: "Ready", readyWithImprovements: "Ready with improvements", reviewRequired: "Review required", notReady: "Not ready" }, readinessScore: "Overall technical readiness score", why: "Why this decision was made", strengthsTitle: "Strengths", improvementsTitle: "Recommended improvements", usesTitle: "Recommended placements",
    reasons: { technicalStrong: "The core technical quality is strong.", technicalAdequate: "Technical quality is adequate for digital use.", technicalWeak: "Technical indicators need improvement.", categoryConfirmed: "The category was confirmed by the user.", categoryUnconfirmed: "The provisional category is not confirmed yet.", compatible: "The category is compatible with platform activity.", compatibilityReview: "Compatibility needs a human decision.", incompatible: "The content was manually marked incompatible.", conversionAvailable: "WebP can improve file efficiency.", conversionCompleted: "The file is WebP or was actually converted.", finalCompositionReady: "A final composed image has been approved." }, strengths: { resolution: "Good resolution", fileSize: "Suitable file size", format: "Efficient web format", cardRatio: "Suitable display frame", compatibility: "Confirmed compatibility", finalComposition: "Final image ready" }, improvements: { confirmCategory: "Confirm product category", reviewCompatibility: "Review category compatibility", convertWebp: "Convert to WebP", increaseResolution: "Use a higher-resolution image", compressFile: "Compress the file" }, uses: { productCard: "Product card", gallery: "Image gallery", hero: "Wide hero image", thumbnail: "Thumbnail", manualReview: "Internal review only" }, useAsIs: "Use as is", advisorDisclaimer: "No computer vision, click probability, sales prediction or artistic scoring is connected in this phase.", stagePartial: "Partial", stageDetails: { contentPartial: "Local provisional category with user confirmation; real vision comes later.", compatibilityReady: "Rule-based compatibility with admin override.", backgroundPartial: "Transparent product extraction must be approved before entering the studio.", conversionReady: "Real local WebP conversion through Canvas.", advisorReady: "Deterministic, explainable technical Decision Engine." },
  },
  fr: {
    contentTitle: "Analyse du contenu de l’image", provisionalBadge: "Analyse locale provisoire", provisionalExplanation: "La catégorie provisoire repose uniquement sur le nom du fichier et le choix utilisateur. La vision réelle sera connectée plus tard.", categoryLabel: "Catégorie provisoire", categorySource: "Source de la catégorie", categorySources: { user: "Choix utilisateur", "local-heuristic": "Règle locale", "future-ai": "Future vision IA" }, categories: { candles: "Bougies", packaging: "Emballages", gifts: "Cadeaux", children: "Enfants et éducation", decoration: "Décoration", services: "Services", "gypsum-decor": "Décor en plâtre", other: "Autre" }, confirmCategory: "Confirmer la catégorie", confirmed: "Confirmée",
    compatibilityTitle: "Compatibilité avec la plateforme", compatibility: { compatible: "Compatible", needsReview: "À vérifier", incompatible: "Incompatible", unknown: "Inconnue" }, compatibilityReasons: { compatible: "La catégorie fait partie des activités DekoKraft prises en charge.", needsReview: "Autre nécessite une décision humaine avant utilisation.", incompatible: "La compatibilité a été refusée manuellement.", unknown: "Les informations sont insuffisantes pour décider." }, overrideLabel: "Décision administrateur", overrides: { none: "Aucune dérogation", approved: "Approuver la compatibilité", rejected: "Refuser la compatibilité" },
    backgroundTitle: "Extraction du produit transparent", backgroundExtractionDescription: "Isolez le produit, ajustez les contours, puis validez la version transparente avant le studio d’arrière-plan.", originalImageLabel: "Image originale", transparentPreviewLabel: "Aperçu transparent", backgroundModes: { original: "Conserver l’original", white: "Arrière-plan blanc", transparent: "Arrière-plan transparent", blur: "Flouter l’arrière-plan", remove: "Supprimer l’arrière-plan" }, backgroundHelp: { original: "Affiche l’original sans modification.", white: "Affiche l’image sur un cadre blanc.", transparent: "Sépare localement les arrière-plans simples et affiche une vraie transparence.", blur: "Affiche une copie floutée derrière l’original.", remove: "La suppression nécessite un véritable fournisseur ultérieurement." }, comingSoon: "Bientôt",
    transparentReal: "Véritable arrière-plan transparent", backgroundProcessing: "Séparation locale du produit et de l’arrière-plan…", transparentReady: "L’aperçu transparent est prêt", backgroundTolerance: "Tolérance de l’arrière-plan", edgeSoftness: "Douceur des contours", productDetailProtection: "Protéger les détails du produit", previewBackground: "Fond de l’aperçu", previewCheckerboard: "Damier", previewDark: "Aperçu sombre", previewLight: "Aperçu clair", compareBeforeAfter: "Comparer avant et après", approveTransparent: "Valider le produit transparent", transparentApproved: "Produit transparent validé", backgroundComplex: "L’arrière-plan est complexe. Une suppression par IA sera nécessaire.", backgroundHeuristicNotice: "Il s’agit d’un traitement local préliminaire pour les arrière-plans simples.", backgroundError: "Le traitement local de l’arrière-plan a échoué.", shadowMode: "Traitement de l’ombre", shadowKeep: "Conserver l’ombre", shadowSoften: "Atténuer l’ombre", shadowRemoveExperimental: "Supprimer l’ombre expérimentalement", shadowExperimentalWarning: "La suppression de l’ombre est expérimentale. Seule la couche d’ombre est supprimée ; le produit reste inchangé.", highSensitivityWarning: "Une sensibilité élevée peut supprimer des parties du produit.", unsafeSensitivityWarning: "La sensibilité est trop élevée et peut supprimer des parties du produit. Réduisez-la à 85 ou moins avant validation.", extractionUnapproved: "Aperçu non validé", extractionApproved: "Produit transparent validé", naturalShadowAdvice: "Conserver une ombre naturelle vaut mieux que supprimer des détails du produit.",
    conversionTitle: "Conversion WebP et compression", quality: "Qualité WebP", convert: "Convertir en WebP", converting: "Conversion…", download: "Télécharger WebP", useConverted: "Utiliser le fichier converti", conversionError: "La conversion WebP a échoué.", gifWarning: "Les GIF animés ne sont pas convertis automatiquement en image statique.", originalFormat: "Format original", outputFormat: "Format de sortie", originalSize: "Taille originale", convertedSize: "Taille convertie", saved: "Économie", outputDimensions: "Dimensions de sortie", noConversion: "Aucun fichier WebP généré.",
    advisorTitle: "DekoBrain Advisor", advisorSubtitle: "Décision technique locale explicable du Decision Engine, sans jugement esthétique ou commercial.", verdicts: { ready: "Prêt", readyWithImprovements: "Prêt avec améliorations", reviewRequired: "Révision requise", notReady: "Non prêt" }, readinessScore: "Score global de préparation technique", why: "Pourquoi cette décision ?", strengthsTitle: "Points forts", improvementsTitle: "Améliorations recommandées", usesTitle: "Emplacements recommandés",
    reasons: { technicalStrong: "La qualité technique de base est forte.", technicalAdequate: "La qualité technique convient à un usage numérique.", technicalWeak: "Les indicateurs techniques doivent être améliorés.", categoryConfirmed: "La catégorie a été confirmée.", categoryUnconfirmed: "La catégorie provisoire n’est pas encore confirmée.", compatible: "La catégorie est compatible avec la plateforme.", compatibilityReview: "La compatibilité nécessite une décision humaine.", incompatible: "Le contenu a été marqué incompatible manuellement.", conversionAvailable: "WebP peut améliorer l’efficacité du fichier.", conversionCompleted: "Le fichier est WebP ou a réellement été converti.", finalCompositionReady: "Une composition finale a été validée." }, strengths: { resolution: "Bonne résolution", fileSize: "Taille adaptée", format: "Format web efficace", cardRatio: "Cadre d’affichage adapté", compatibility: "Compatibilité confirmée", finalComposition: "Image finale prête" }, improvements: { confirmCategory: "Confirmer la catégorie", reviewCompatibility: "Vérifier la compatibilité", convertWebp: "Convertir en WebP", increaseResolution: "Utiliser une résolution supérieure", compressFile: "Compresser le fichier" }, uses: { productCard: "Carte produit", gallery: "Galerie", hero: "Image principale large", thumbnail: "Miniature", manualReview: "Révision interne uniquement" }, useAsIs: "Utiliser tel quel", advisorDisclaimer: "Aucune vision par ordinateur, probabilité de clic, prévision de vente ou note artistique n’est connectée.", stagePartial: "Partiel", stageDetails: { contentPartial: "Catégorie locale provisoire avec confirmation ; vision réelle ultérieure.", compatibilityReady: "Compatibilité par règles avec dérogation administrateur.", backgroundPartial: "L’extraction transparente doit être validée avant le studio.", conversionReady: "Conversion WebP locale réelle via Canvas.", advisorReady: "Decision Engine technique, déterministe et explicable." },
  },
};
