import type { Lang } from "./translations";
export type MarketingContent={productName:string;shortDescription:string;marketingHeadline:string;marketingParagraph:string;poem:string;hashtags:string[];priceSuggestion:string;callToAction:string};
export interface MarketingStudioCopy {studioTitle:string;title:string;description:string;generate:string;generateAnother:string;copy:string;copied:string;needsApprovedImage:string;fields:Record<keyof MarketingContent,string>;demos:MarketingContent[]}
export const dekoBrainMarketingTranslations:Record<Lang,MarketingStudioCopy>={
 ar:{studioTitle:"🧠 استوديو التسويق الذكي",title:"✨ إنشاء محتوى تسويقي بالذكاء الاصطناعي",description:"يقوم DekoBrain بتحليل المنتج والصورة المعتمدة ثم يقترح محتوى إعلاني احترافي يمكن إرساله مباشرة إلى Canva.",generate:"🧠 إنشاء المحتوى",generateAnother:"✨ إنشاء نسخة أخرى",copy:"نسخ",copied:"تم النسخ",needsApprovedImage:"اعتمد المنتج الشفاف أو الصورة النهائية أولًا.",fields:{productName:"اسم المنتج",shortDescription:"الوصف",marketingHeadline:"العنوان",marketingParagraph:"النص التسويقي",poem:"القصيدة",hashtags:"الهاشتاغات",priceSuggestion:"السعر المقترح",callToAction:"الدعوة إلى الإجراء"},demos:[
  {productName:"شمعة العسل الفاخرة",shortDescription:"شمعة يدوية تضيف دفئًا وأناقة لكل زاوية.",marketingHeadline:"أضئ منزلك بلمسة فاخرة.",marketingParagraph:"شموع طبيعية مصنوعة بعناية لتمنح المكان هدوءًا وجمالًا.",poem:"حين يهدأ المساء\nتولد الحكايات مع الضوء.",hashtags:["#شموع","#ديكور","#هدايا","#DekoKraft"],priceSuggestion:"12.90 €",callToAction:"اطلبها الآن."},
  {productName:"هدية مصنوعة بمحبة",shortDescription:"هدية شخصية تحمل تفاصيلك الجميلة.",marketingHeadline:"لأن أجمل الهدايا تحكي قصة.",marketingParagraph:"حوّل لحظتك الخاصة إلى هدية فريدة مصنوعة بعناية خصيصًا لمن تحب.",poem:"تفصيل صغير من القلب\nيبقى في الذاكرة طويلًا.",hashtags:["#هدايا_مخصصة","#صناعة_يدوية","#حب","#DekoKraft"],priceSuggestion:"19.90 €",callToAction:"صمّم هديتك اليوم."},
  {productName:"صندوق الذكريات الخشبي",shortDescription:"صندوق أنيق لحفظ اللحظات والهدايا الثمينة.",marketingHeadline:"احتفظ باللحظات في مكان يليق بها.",marketingParagraph:"خشب دافئ وتصميم شخصي يجعلان كل ذكرى أقرب إلى القلب.",poem:"ما تحفظه اليد بحنان\nيحفظه القلب إلى الأبد.",hashtags:["#خشب","#ذكريات","#تخصيص","#DekoKraft"],priceSuggestion:"24.50 €",callToAction:"اختر نقشَك الآن."},
  {productName:"ديكور المنزل الهادئ",shortDescription:"قطعة ديكور بسيطة تمنح المساحة روحًا دافئة.",marketingHeadline:"تفاصيل صغيرة، فرق كبير.",marketingParagraph:"أضف لمسة حرفية هادئة تعكس ذوقك وتحوّل الزاوية إلى مساحة محببة.",poem:"في زاوية البيت نور\nوفي التفاصيل حياة.",hashtags:["#ديكور_منزلي","#حرفيون","#تصميم","#DekoKraft"],priceSuggestion:"16.90 €",callToAction:"اكتشفها الآن."}
 ]},
 de:{studioTitle:"🧠 AI Marketing Studio",title:"✨ Marketinginhalte mit KI erstellen",description:"DekoBrain analysiert das Produkt und das freigegebene Bild und schlägt professionelle Werbeinhalte vor, die direkt für Canva vorbereitet sind.",generate:"🧠 Inhalt erstellen",generateAnother:"✨ Weitere Variante erstellen",copy:"Kopieren",copied:"Kopiert",needsApprovedImage:"Bitte zuerst das transparente Produkt oder das finale Bild freigeben.",fields:{productName:"Produktname",shortDescription:"Kurzbeschreibung",marketingHeadline:"Headline",marketingParagraph:"Marketingtext",poem:"Gedicht",hashtags:"Hashtags",priceSuggestion:"Preisvorschlag",callToAction:"Handlungsaufforderung"},demos:makeGermanDemos()},
 en:{studioTitle:"🧠 AI Marketing Studio",title:"✨ Create AI marketing content",description:"DekoBrain analyzes the product and approved image, then suggests professional advertising content ready to send to Canva.",generate:"🧠 Create content",generateAnother:"✨ Create another version",copy:"Copy",copied:"Copied",needsApprovedImage:"Approve the transparent product or final image first.",fields:{productName:"Product name",shortDescription:"Short description",marketingHeadline:"Headline",marketingParagraph:"Marketing copy",poem:"Poem",hashtags:"Hashtags",priceSuggestion:"Price suggestion",callToAction:"Call to action"},demos:makeEnglishDemos()},
 fr:{studioTitle:"🧠 Studio marketing IA",title:"✨ Créer du contenu marketing avec l’IA",description:"DekoBrain analyse le produit et l’image validée, puis propose un contenu publicitaire professionnel prêt pour Canva.",generate:"🧠 Créer le contenu",generateAnother:"✨ Créer une autre version",copy:"Copier",copied:"Copié",needsApprovedImage:"Validez d’abord le produit transparent ou l’image finale.",fields:{productName:"Nom du produit",shortDescription:"Description courte",marketingHeadline:"Titre",marketingParagraph:"Texte marketing",poem:"Poème",hashtags:"Hashtags",priceSuggestion:"Prix suggéré",callToAction:"Appel à l’action"},demos:makeFrenchDemos()}
};

function makeEnglishDemos():MarketingContent[]{return [
 {productName:"Luxury Honey Candle",shortDescription:"A handmade candle that adds warmth and elegance to every corner.",marketingHeadline:"Light your home with a luxurious touch.",marketingParagraph:"Natural candles crafted with care to bring calm and beauty into your space.",poem:"When evening settles low,\nstories awaken in the glow.",hashtags:["#Candles","#Decor","#Gifts","#DekoKraft"],priceSuggestion:"12.90 €",callToAction:"Order yours now."},
 {productName:"A Gift Made with Love",shortDescription:"A personalized gift shaped around your story.",marketingHeadline:"The best gifts tell a story.",marketingParagraph:"Turn a special moment into a unique handcrafted keepsake for someone you love.",poem:"A detail chosen from the heart\nkeeps every memory close.",hashtags:["#PersonalizedGift","#Handmade","#Love","#DekoKraft"],priceSuggestion:"19.90 €",callToAction:"Design your gift today."},
 {productName:"Wooden Memory Box",shortDescription:"An elegant box for treasured moments and meaningful gifts.",marketingHeadline:"Keep every memory somewhere beautiful.",marketingParagraph:"Warm wood and personal engraving make your memories feel even closer.",poem:"What gentle hands preserve,\nthe heart remembers forever.",hashtags:["#Wood","#Memories","#Personalized","#DekoKraft"],priceSuggestion:"24.50 €",callToAction:"Choose your engraving."},
 {productName:"Calm Home Accent",shortDescription:"A simple decorative piece that brings warmth to your space.",marketingHeadline:"Small details make a beautiful difference.",marketingParagraph:"Add a quiet handcrafted touch that reflects your style and transforms any corner.",poem:"A little light at home,\na little life in every detail.",hashtags:["#HomeDecor","#Artisan","#Design","#DekoKraft"],priceSuggestion:"16.90 €",callToAction:"Discover it now."}
]}
function makeGermanDemos():MarketingContent[]{return [
 {productName:"Luxuriöse Honigkerze",shortDescription:"Handgefertigte Kerze für Wärme und Eleganz.",marketingHeadline:"Ein luxuriöses Licht für Ihr Zuhause.",marketingParagraph:"Mit Sorgfalt gefertigte Naturkerzen schenken Ruhe und Schönheit.",poem:"Wenn der Abend leiser wird,\nerwachen Geschichten im Licht.",hashtags:["#Kerzen","#Dekoration","#Geschenke","#DekoKraft"],priceSuggestion:"12,90 €",callToAction:"Jetzt bestellen."},
 {productName:"Geschenk mit Liebe",shortDescription:"Ein persönliches Geschenk für Ihre besondere Geschichte.",marketingHeadline:"Die schönsten Geschenke erzählen Geschichten.",marketingParagraph:"Verwandeln Sie einen besonderen Moment in ein liebevoll gefertigtes Unikat.",poem:"Ein Detail, von Herzen gewählt,\nhält Erinnerungen ganz nah.",hashtags:["#Personalisiert","#Handgemacht","#Liebe","#DekoKraft"],priceSuggestion:"19,90 €",callToAction:"Heute gestalten."},
 {productName:"Hölzerne Erinnerungsbox",shortDescription:"Eine elegante Box für wertvolle Momente und Geschenke.",marketingHeadline:"Bewahren Sie Erinnerungen stilvoll auf.",marketingParagraph:"Warmes Holz und eine persönliche Gravur geben jeder Erinnerung einen besonderen Platz.",poem:"Was Hände sorgsam bewahren,\nträgt das Herz für immer.",hashtags:["#Holz","#Erinnerungen","#Gravur","#DekoKraft"],priceSuggestion:"24,50 €",callToAction:"Gravur auswählen."},
 {productName:"Ruhige Wohnakzente",shortDescription:"Ein schlichtes Dekostück für eine warme Atmosphäre.",marketingHeadline:"Kleine Details, große Wirkung.",marketingParagraph:"Ein handgefertigter Akzent verwandelt jede Ecke in einen persönlichen Lieblingsplatz.",poem:"Ein Licht im stillen Raum,\nLeben in jedem Detail.",hashtags:["#Wohndekoration","#Handwerk","#Design","#DekoKraft"],priceSuggestion:"16,90 €",callToAction:"Jetzt entdecken."}
]}
function makeFrenchDemos():MarketingContent[]{return [
 {productName:"Bougie au miel raffinée",shortDescription:"Une bougie artisanale qui apporte chaleur et élégance.",marketingHeadline:"Illuminez votre intérieur avec raffinement.",marketingParagraph:"Des bougies naturelles créées avec soin pour une ambiance paisible.",poem:"Quand le soir devient silence,\nles histoires naissent dans la lumière.",hashtags:["#Bougies","#Décoration","#Cadeaux","#DekoKraft"],priceSuggestion:"12,90 €",callToAction:"Commandez maintenant."},
 {productName:"Cadeau créé avec amour",shortDescription:"Un cadeau personnalisé qui raconte votre histoire.",marketingHeadline:"Les plus beaux cadeaux racontent une histoire.",marketingParagraph:"Transformez un moment précieux en souvenir artisanal unique pour une personne chère.",poem:"Un détail choisi par le cœur\ngarde les souvenirs tout près.",hashtags:["#CadeauPersonnalisé","#Artisanal","#Amour","#DekoKraft"],priceSuggestion:"19,90 €",callToAction:"Créez le vôtre aujourd’hui."},
 {productName:"Boîte à souvenirs en bois",shortDescription:"Une boîte élégante pour les moments et cadeaux précieux.",marketingHeadline:"Gardez vos souvenirs dans un bel écrin.",marketingParagraph:"Le bois chaleureux et la gravure personnelle donnent une place unique à chaque souvenir.",poem:"Ce que les mains préservent,\nle cœur le garde toujours.",hashtags:["#Bois","#Souvenirs","#Gravure","#DekoKraft"],priceSuggestion:"24,50 €",callToAction:"Choisissez votre gravure."},
 {productName:"Décoration intérieure apaisante",shortDescription:"Une pièce simple qui apporte chaleur et sérénité.",marketingHeadline:"Les petits détails font la différence.",marketingParagraph:"Ajoutez une touche artisanale qui reflète votre style et transforme chaque coin.",poem:"Une lumière dans la maison,\nune vie dans chaque détail.",hashtags:["#Décoration","#Artisanat","#Design","#DekoKraft"],priceSuggestion:"16,90 €",callToAction:"Découvrez-la maintenant."}
]}
