export type ExtractionMasks={productMask:ImageData|null;shadowMask:ImageData|null};

export function extractProductAndShadowMasks(sourceCanvas:HTMLCanvasElement,settings:{backgroundSensitivity:number;edgeSoftness:number;detailProtection:number}):ExtractionMasks{
 const context=sourceCanvas.getContext("2d",{willReadFrequently:true});if(!context)return{productMask:null,shadowMask:null};const width=sourceCanvas.width,height=sourceCanvas.height,source=context.getImageData(0,0,width,height),data=source.data,pixels=width*height;
 const sample=Math.max(2,Math.min(24,Math.round(Math.min(width,height)*.04))),colors:Array<[number,number,number]>=[];const corners=[[0,0],[width-sample,0],[0,height-sample],[width-sample,height-sample]];
 for(const [sx,sy] of corners)for(let y=sy;y<sy+sample;y+=2)for(let x=sx;x<sx+sample;x+=2){const o=(y*width+x)*4;if(data[o+3]>16)colors.push([data[o],data[o+1],data[o+2]]);}if(!colors.length)return{productMask:null,shadowMask:null};
 const median=(channel:number)=>colors.map(c=>c[channel]).sort((a,b)=>a-b)[Math.floor(colors.length/2)];const bg=[median(0),median(1),median(2)],distance=(i:number)=>{const o=i*4;return Math.hypot(data[o]-bg[0],data[o+1]-bg[1],data[o+2]-bg[2]);};
 const sensitivity=Math.max(0,Math.min(100,settings.backgroundSensitivity)),softness=Math.max(0,Math.min(50,settings.edgeSoftness)),protection=Math.max(50,Math.min(100,settings.detailProtection));const backgroundLimit=Math.max(5,(sensitivity+softness*.35)*(1-(protection-50)*.0045));
 const background=new Uint8Array(pixels),visited=new Uint8Array(pixels),queue:number[]=[];const add=(i:number)=>{if(!visited[i]&&distance(i)<=backgroundLimit){visited[i]=1;queue.push(i);}};for(let x=0;x<width;x++){add(x);add((height-1)*width+x);}for(let y=0;y<height;y++){add(y*width);add(y*width+width-1);}for(let head=0;head<queue.length;head++){const i=queue[head];background[i]=1;const x=i%width,y=Math.floor(i/width);if(x)add(i-1);if(x+1<width)add(i+1);if(y)add(i-width);if(y+1<height)add(i+width);}
 const shadow=new Uint8Array(pixels),shadowLimit=backgroundLimit+Math.max(6,22-(protection-50)*.2);for(let pass=0;pass<4;pass++)for(let i=0;i<pixels;i++){if(background[i]||shadow[i]||distance(i)>shadowLimit)continue;const x=i%width,y=Math.floor(i/width);if(y<height*.42)continue;const o=i*4;const max=Math.max(data[o],data[o+1],data[o+2]),min=Math.min(data[o],data[o+1],data[o+2]);if(max-min>42)continue;const adjacent=(x>0&&(background[i-1]||shadow[i-1]))||(x+1<width&&(background[i+1]||shadow[i+1]))||(y>0&&(background[i-width]||shadow[i-width]))||(y+1<height&&(background[i+width]||shadow[i+width]));if(adjacent)shadow[i]=1;}
 const productData=new Uint8ClampedArray(data.length),shadowData=new Uint8ClampedArray(data.length);for(let i=0;i<pixels;i++){const o=i*4;productData[o]=productData[o+1]=productData[o+2]=255;shadowData[o]=shadowData[o+1]=shadowData[o+2]=255;if(!background[i]&&!shadow[i])productData[o+3]=data[o+3];if(shadow[i])shadowData[o+3]=data[o+3];}
 return{productMask:new ImageData(productData,width,height),shadowMask:new ImageData(shadowData,width,height)};
}
