import type { DetectedFeature,ProductCategory,ProductFeatureKey,ProductProfile } from "./productAnalyzerTypes";
type AnalyzeInput={image:string;fileName:string;mimeType:string;userCategory?:string};
const clamp=(value:number)=>Math.max(0,Math.min(1,value));
function loadImage(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("product-analysis-image-load-failed"));image.src=url;});}
export function inferProductCategoryFromText(value:string):ProductCategory{const text=value.toLowerCase();if(/gypsum|plaster decor|gipsdeko|gips decor|décor en plâtre|ديكور من الجبس|ديكور جبسي|جبس/.test(text))return"gypsum-decor";if(/candle|candles|candel|candels|شمعة|شموع|kerze|bougie/.test(text))return"candle";if(/flower|rose|floral|ورد|زهرة|blume|fleur/.test(text))return"flower";if(/glass|transparent|زجاج|glas|verre/.test(text))return"glass";if(/jewel|ring|necklace|مجوهر|schmuck|bijou/.test(text))return"jewelry";if(/box|giftbox|صندوق|علبة|schachtel|boîte/.test(text))return"box";if(/fabric|textile|قماش|stoff|tissu/.test(text))return"fabric";if(/toy|kids|لعبة|أطفال|spielzeug|jouet/.test(text))return"toy";if(/food|cake|طعام|essen|aliment/.test(text))return"food";if(/phone|electronic|هاتف|elektronik|électronique/.test(text))return"electronics";if(/furniture|chair|أثاث|möbel|meuble/.test(text))return"furniture";return"unknown";}
function feature(key:ProductFeatureKey,detected:boolean,confidence:number,source:DetectedFeature["source"]):DetectedFeature{return{key,detected,confidence:clamp(confidence),source};}
export async function analyzeProductImage({image,fileName,mimeType,userCategory}:AnalyzeInput):Promise<ProductProfile>{
 const userDetected=userCategory?inferProductCategoryFromText(userCategory):"unknown",filenameDetected=inferProductCategoryFromText(fileName),category=userDetected!=="unknown"?userDetected:filenameDetected,categorySource=userDetected!=="unknown"?"user":filenameDetected!=="unknown"?"filename":"fallback";let categoryConfidence=userDetected!=="unknown"?.96:filenameDetected!=="unknown"?.86:.2;
 const loaded=await loadImage(image);const max=256,ratio=Math.min(1,max/Math.max(loaded.naturalWidth,loaded.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(loaded.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(loaded.naturalHeight*ratio));const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)throw new Error("product-analysis-canvas-unavailable");context.clearRect(0,0,canvas.width,canvas.height);context.drawImage(loaded,0,0,canvas.width,canvas.height);const data=context.getImageData(0,0,canvas.width,canvas.height).data;
 const edgeColors:number[][]=[];let warmBright=0,bottomShadow=0,transparent=0;const pixels=canvas.width*canvas.height;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const o=(y*canvas.width+x)*4,r=data[o],g=data[o+1],b=data[o+2],a=data[o+3];if(x<3||y<3||x>=canvas.width-3||y>=canvas.height-3)edgeColors.push([r,g,b]);if(y<canvas.height*.48&&r>190&&g>90&&g<210&&b<120&&r>g*1.15)warmBright++;if(y>canvas.height*.68&&Math.max(r,g,b)-Math.min(r,g,b)<38&&(r+g+b)/3<150)bottomShadow++;if(a<245)transparent++;}
 const means=[0,1,2].map(channel=>edgeColors.reduce((sum,color)=>sum+color[channel],0)/Math.max(1,edgeColors.length));const edgeVariance=Math.sqrt(edgeColors.reduce((sum,color)=>sum+color.reduce((inner,value,index)=>inner+(value-means[index])**2,0),0)/Math.max(1,edgeColors.length));const edgeBrightness=means.reduce((a,b)=>a+b,0)/3;const whiteBackground=edgeBrightness>232&&edgeVariance<30,complexBackground=edgeVariance>58;const flameConfidence=clamp(warmBright/pixels*55+(category==="candle"?.45:0));const shadowConfidence=clamp(bottomShadow/pixels*16);const name=fileName.toLowerCase();
 const features:DetectedFeature[]=[feature("whiteBackground",whiteBackground,whiteBackground?.9:.25,"pixels"),feature("complexBackground",complexBackground,clamp(edgeVariance/100),"pixels"),feature("flame",flameConfidence>=.52,flameConfidence,"pixels"),feature("softShadow",shadowConfidence>=.3,shadowConfidence,"pixels"),feature("transparency",transparent/pixels>.01,clamp(transparent/pixels*8),mimeType.includes("png")?"metadata":"pixels"),feature("thinEdges",category==="candle"||category==="flower"||category==="jewelry",category==="candle"?.8:category==="flower"?.88:.55,categorySource),feature("fineTexture",category==="flower"||category==="fabric",category==="flower"?.86:category==="fabric"?.9:.15,categorySource),feature("petals",category==="flower",category==="flower"?.92:.08,categorySource),feature("glass",category==="glass",category==="glass"?.92:.08,categorySource),feature("wood",/wood|holz|خشب|bois/.test(name),.82,"filename"),feature("metal",/metal|stahl|حديد|métal/.test(name),.8,"filename"),feature("fabric",category==="fabric",category==="fabric"?.92:.08,categorySource),feature("roundShape",loaded.naturalWidth/loaded.naturalHeight>.82&&loaded.naturalWidth/loaded.naturalHeight<1.18,.55,"metadata"),feature("tallShape",loaded.naturalHeight>loaded.naturalWidth*1.25,.75,"metadata"),feature("reflection",category==="glass"||category==="jewelry",category==="glass"?.78:.58,categorySource),feature("hardShadow",false,.15,"fallback")];
 const flame=features.find(item=>item.key==="flame")?.detected??false,fineTexture=features.some(item=>item.detected&&["fineTexture","petals","fabric"].includes(item.key));const delicate=category==="gypsum-decor"||category==="candle"||category==="flower"||flame||fineTexture;const warnings:string[]=[];if(complexBackground)warnings.push("complexBackgroundReview");if(flame)warnings.push("possibleFlamePreserved");if(category==="unknown")warnings.push("lowCategoryConfidence");
 if(category==="unknown"&&complexBackground)categoryConfidence=.15;
 return{category,categoryConfidence:clamp(categoryConfidence),categorySource,features,protection:{preserveFlame:category==="candle"||flame,preserveThinEdges:delicate||category==="jewelry",preserveFineTexture:fineTexture,preserveReflection:category==="glass"||category==="jewelry",preserveNaturalShadow:delicate||shadowConfidence>.3,allowAggressiveBackgroundRemoval:!delicate&&!complexBackground&&category!=="unknown"},recommendation:{backgroundRemovalMode:delicate?"gentle":"balanced",shadowMode:category==="gypsum-decor"?"soften":delicate?"keep":shadowConfidence>.55?"soften":"keep",cropMode:delicate?"contain":"smart",enhancementMode:category==="candle"?"warm":"natural",warnings},analyzedAt:new Date().toISOString(),analyzerVersion:"1.0.0-local"};
}
export function getDetectedFeature(profile:ProductProfile,key:ProductFeatureKey){return profile.features.find(feature=>feature.key===key);}
export function getProductProfileSummary(profile:ProductProfile){return{category:profile.category,confidence:profile.categoryConfidence,detectedFeatureKeys:profile.features.filter(feature=>feature.detected).map(feature=>feature.key),protectionKeys:Object.entries(profile.protection).filter(([,enabled])=>enabled).map(([key])=>key),recommendation:profile.recommendation};}
