import { extractProductAndShadowMasks } from "./extractProductAndShadowMasks";
export type RemoveBackgroundOptions={threshold?:number;softness?:number;protection?:number;shadowMode?:"keep"|"soften"|"experimental-remove"};
export type SimpleBackgroundResult={blob:Blob;productBlob:Blob;shadowBlob:Blob;blurredBlob:Blob;cornerVariance:number;isComplex:boolean};
function loadImage(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("background-image-load-failed"));image.src=url;});}
function toBlob(canvas:HTMLCanvasElement){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("background-export-failed")),"image/png"));}
function maskedLayer(source:ImageData,mask:ImageData){const canvas=document.createElement("canvas");canvas.width=source.width;canvas.height=source.height;const context=canvas.getContext("2d");if(!context)throw new Error("background-canvas-unavailable");const output=new ImageData(new Uint8ClampedArray(source.data),source.width,source.height);for(let i=0;i<output.data.length;i+=4)output.data[i+3]=Math.round(output.data[i+3]*(mask.data[i+3]/255));context.putImageData(output,0,0);return canvas;}
export async function composeExtractionLayers(productBlob:Blob,shadowBlob:Blob,mode:RemoveBackgroundOptions["shadowMode"]="keep"){const productUrl=URL.createObjectURL(productBlob),shadowUrl=URL.createObjectURL(shadowBlob);try{const [product,shadow]=await Promise.all([loadImage(productUrl),loadImage(shadowUrl)]);const canvas=document.createElement("canvas");canvas.width=product.naturalWidth;canvas.height=product.naturalHeight;const context=canvas.getContext("2d");if(!context)throw new Error("background-canvas-unavailable");context.clearRect(0,0,canvas.width,canvas.height);if(mode!=="experimental-remove"){context.save();context.globalAlpha=mode==="soften"?.35:1;if(mode==="soften")context.filter="blur(3px)";context.drawImage(shadow,0,0);context.restore();}context.drawImage(product,0,0);return toBlob(canvas);}finally{URL.revokeObjectURL(productUrl);URL.revokeObjectURL(shadowUrl);}}
export async function removeSimpleBackgroundWithAnalysis(sourceUrl:string,options:RemoveBackgroundOptions={}):Promise<SimpleBackgroundResult>{const image=await loadImage(sourceUrl);const sourceCanvas=document.createElement("canvas");sourceCanvas.width=image.naturalWidth;sourceCanvas.height=image.naturalHeight;const context=sourceCanvas.getContext("2d",{willReadFrequently:true});if(!context)throw new Error("background-canvas-unavailable");context.clearRect(0,0,sourceCanvas.width,sourceCanvas.height);context.drawImage(image,0,0);const source=context.getImageData(0,0,sourceCanvas.width,sourceCanvas.height);const masks=extractProductAndShadowMasks(sourceCanvas,{backgroundSensitivity:options.threshold??42,edgeSoftness:options.softness??28,detailProtection:options.protection??85});if(!masks.productMask||!masks.shadowMask)throw new Error("background-mask-failed");const productCanvas=maskedLayer(source,masks.productMask),shadowCanvas=maskedLayer(source,masks.shadowMask),productBlob=await toBlob(productCanvas),shadowBlob=await toBlob(shadowCanvas),blob=await composeExtractionLayers(productBlob,shadowBlob,options.shadowMode??"keep");return{blob,productBlob,shadowBlob,blurredBlob:blob,cornerVariance:0,isComplex:false};}
export async function removeSimpleBackground(sourceUrl:string,options?:RemoveBackgroundOptions){return(await removeSimpleBackgroundWithAnalysis(sourceUrl,options)).blob;}
