function loadImage(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("crop-image-load-failed"));image.src=url;});}
function toBlob(canvas:HTMLCanvasElement){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("crop-export-failed")),"image/png"));}
export async function getTransparentAlphaBounds(sourceUrl:string){const image=await loadImage(sourceUrl);const canvas=document.createElement("canvas");canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)throw new Error("crop-canvas-unavailable");context.clearRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0);const data=context.getImageData(0,0,canvas.width,canvas.height).data;let minX=canvas.width,minY=canvas.height,maxX=-1,maxY=-1,hasTransparent=false;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const alpha=data[(y*canvas.width+x)*4+3];if(alpha<250)hasTransparent=true;if(alpha>12){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}}if(!hasTransparent||maxX<minX||maxY<minY)throw new Error("crop-no-alpha");return{sourceWidth:canvas.width,sourceHeight:canvas.height,minX,minY,maxX,maxY,width:maxX-minX+1,height:maxY-minY+1};}
export async function smartCropTransparent(sourceUrl:string,paddingRatio=.05){
 const image=await loadImage(sourceUrl);const canvas=document.createElement("canvas");canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)throw new Error("crop-canvas-unavailable");context.drawImage(image,0,0);const data=context.getImageData(0,0,canvas.width,canvas.height).data;
 let minX=canvas.width,minY=canvas.height,maxX=-1,maxY=-1,hasTransparent=false;
 for(let y=0;y<canvas.height;y++){for(let x=0;x<canvas.width;x++){const alpha=data[(y*canvas.width+x)*4+3];if(alpha<250)hasTransparent=true;if(alpha>8){if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y;}}}
 if(!hasTransparent||maxX<minX||maxY<minY)throw new Error("crop-no-alpha");
 const contentWidth=maxX-minX+1,contentHeight=maxY-minY+1;const ratio=Math.min(.06,Math.max(.04,paddingRatio)),paddingX=Math.round(contentWidth*ratio),paddingY=Math.round(contentHeight*ratio);const sourceX=Math.max(0,minX-paddingX),sourceY=Math.max(0,minY-paddingY);const sourceWidth=Math.min(canvas.width-sourceX,contentWidth+paddingX*2),sourceHeight=Math.min(canvas.height-sourceY,contentHeight+paddingY*2);
 const output=document.createElement("canvas");output.width=sourceWidth;output.height=sourceHeight;const outputContext=output.getContext("2d");if(!outputContext)throw new Error("crop-canvas-unavailable");outputContext.drawImage(image,sourceX,sourceY,sourceWidth,sourceHeight,0,0,sourceWidth,sourceHeight);
 return {blob:await toBlob(output),width:sourceWidth,height:sourceHeight};
}
