// Barrel for presentational Magic Engine UI components and local Magic Creator data.
// UI components exported here receive props and should not calculate product state.
export { AutoFixPlanCard } from "./AutoFixPlanCard";
export { default as AssistantSection } from "./AssistantSection";
export { default as CreatorTodayFocusCard } from "./CreatorTodayFocusCard";
export { default as CreatorWorkspacePreview } from "./CreatorWorkspacePreview";
export * from "./decisionEngine";
export { EstimatedTimeCard } from "./EstimatedTimeCard";
export * from "./configurationEngine";
export { default as LearningCard } from "./LearningCard";
export { MagicConfidenceCard } from "./MagicConfidenceCard";
export { MagicCreatorSkeleton } from "./MagicCreatorSkeleton";
export * from "./magicCreatorData";
export * from "./magicCreatorSamples";
export * from "./magicCreatorTypes";
export * from "./pricingEngine";
export * from "./wizardEngine";
export { MagicDashboard } from "./MagicDashboard";
export { default as MagicEngineActionBar } from "./MagicEngineActionBar";
export { default as MagicEngineAssistantPanel } from "./MagicEngineAssistantPanel";
export { default as MagicEngineHeader } from "./MagicEngineHeader";
export { default as MagicEngineSectionTitle } from "./MagicEngineSectionTitle";
export { default as MagicEngineStatusStrip } from "./MagicEngineStatusStrip";
export { MagicProgressCard } from "./MagicProgressCard";
export { MagicRecommendationsCard } from "./MagicRecommendationsCard";
export { MarketPotentialCard } from "./MarketPotentialCard";
export { NextBestActionCard } from "./NextBestActionCard";
export { default as OpportunityCard } from "./OpportunityCard";
export { OverallStatusCard } from "./OverallStatusCard";
export { ProductHealthCard } from "./ProductHealthCard";
export { default as ProjectProgressCard } from "./ProjectProgressCard";
export { PublishChecklistCard } from "./PublishChecklistCard";
export { PublishStatusCards } from "./PublishStatusCards";
export { default as QuickActionsSection } from "./QuickActionsSection";
export { default as RecentActivityCard } from "./RecentActivityCard";
export { default as StudioHealthCard } from "./StudioHealthCard";
export { default as SystemStatusSection } from "./SystemStatusSection";
export { default as WorkspaceOverviewSection } from "./WorkspaceOverviewSection";
export { default as WorkspaceReadinessCard } from "./WorkspaceReadinessCard";
