import {
  type EngineStepId,
  type EngineStepStatus,
  type MagicEngineStep,
} from "./types";

const defaultStatus: EngineStepStatus = "notStarted";

export const magicEngineSteps: MagicEngineStep[] = [
  {
    id: "images",
    title: {
      ar: "الصور",
      en: "Images",
      de: "Bilder",
      fr: "Images",
    },
    description: {
      ar: "رفع صور المنتج وتنظيمها حسب الدور والترتيب.",
      en: "Upload product images and organize them by role and order.",
      de: "Produktbilder hochladen und nach Rolle und Reihenfolge organisieren.",
      fr: "Importer les images du produit et les organiser par role et ordre.",
    },
    status: defaultStatus,
  },
  {
    id: "specifications",
    title: {
      ar: "المواصفات",
      en: "Specifications",
      de: "Spezifikationen",
      fr: "Specifications",
    },
    description: {
      ar: "كتابة مواصفات المنتج بلغة طبيعية.",
      en: "Write product specifications in natural language.",
      de: "Produktspezifikationen in natürlicher Sprache schreiben.",
      fr: "Rediger les specifications du produit en langage naturel.",
    },
    status: defaultStatus,
  },
  {
    id: "productUnderstanding",
    title: {
      ar: "فهم المنتج",
      en: "Product Understanding",
      de: "Produktverständnis",
      fr: "Compréhension du produit",
    },
    description: {
      ar: "تحويل المدخلات إلى فهم منظم للمنتج.",
      en: "Turn inputs into structured product understanding.",
      de: "Eingaben in ein strukturiertes Produktverständnis umwandeln.",
      fr: "Transformer les entrees en comprehension structuree du produit.",
    },
    status: defaultStatus,
  },
  {
    id: "productCard",
    title: {
      ar: "بطاقة المنتج",
      en: "Product Card",
      de: "Produktkarte",
      fr: "Fiche produit",
    },
    description: {
      ar: "بناء بطاقة منتج مختصرة قابلة للمراجعة.",
      en: "Build a concise reviewable product card.",
      de: "Eine kompakte prüfbare Produktkarte erstellen.",
      fr: "Construire une fiche produit concise et verifiable.",
    },
    status: defaultStatus,
  },
  {
    id: "productBlueprint",
    title: {
      ar: "مخطط المنتج",
      en: "Product Blueprint",
      de: "Produktplan",
      fr: "Fiche complète",
    },
    description: {
      ar: "إنشاء مخطط كامل لبيانات المنتج ومحتواه.",
      en: "Create a complete blueprint for product data and content.",
      de: "Einen vollständigen Plan für Produktdaten und Inhalte erstellen.",
      fr: "Creer une fiche complete pour les donnees et contenus produit.",
    },
    status: defaultStatus,
  },
  {
    id: "productContent",
    title: {
      ar: "محتوى المنتج",
      en: "Product Content",
      de: "Produktinhalt",
      fr: "Contenu produit",
    },
    description: {
      ar: "تحضير وصف المنتج والنقاط التسويقية.",
      en: "Prepare product descriptions and marketing points.",
      de: "Produktbeschreibungen und Marketingpunkte vorbereiten.",
      fr: "Preparer les descriptions produit et arguments marketing.",
    },
    status: defaultStatus,
  },
  {
    id: "seo",
    title: {
      ar: "SEO",
      en: "SEO",
      de: "SEO",
      fr: "SEO",
    },
    description: {
      ar: "تحضير عنوان SEO والوصف والرابط والكلمات المفتاحية.",
      en: "Prepare SEO title, description, slug, and keywords.",
      de: "SEO-Titel, Beschreibung, Slug und Keywords vorbereiten.",
      fr: "Preparer le titre SEO, la description, le slug et les mots-cles.",
    },
    status: defaultStatus,
  },
  {
    id: "aiImages",
    title: {
      ar: "صور الذكاء الاصطناعي",
      en: "AI Images",
      de: "KI-Bilder",
      fr: "Images IA",
    },
    description: {
      ar: "تخطيط صور مستقبلية يمكن توليدها بالذكاء الاصطناعي لاحقًا.",
      en: "Plan future images that can be generated by AI later.",
      de: "Zukünftige Bilder planen, die später mit KI erzeugt werden können.",
      fr: "Planifier les futures images qui pourront etre generees par IA.",
    },
    status: defaultStatus,
  },
  {
    id: "readyToPublish",
    title: {
      ar: "جاهز للنشر",
      en: "Ready to Publish",
      de: "Bereit zur Veröffentlichung",
      fr: "Prêt à publier",
    },
    description: {
      ar: "التأكد من أن المنتج مكتمل وجاهز للمراجعة النهائية.",
      en: "Confirm the product is complete and ready for final review.",
      de: "Bestätigen, dass das Produkt vollständig und bereit zur Endprüfung ist.",
      fr: "Confirmer que le produit est complet et prêt pour la verification finale.",
    },
    status: defaultStatus,
  },
];

export function createMagicEngineSteps(
  statuses: Partial<Record<EngineStepId, EngineStepStatus>> = {}
): MagicEngineStep[] {
  return magicEngineSteps.map((step) => ({
    ...step,
    status: statuses[step.id] || step.status,
  }));
}
