import path from "node:path";

import type { DekoCleanConfig } from "./types.ts";

export function createDekoCleanConfig(
  projectRoot = process.cwd(),
  overrides: Partial<DekoCleanConfig> = {},
): DekoCleanConfig {
  const root = path.resolve(projectRoot);

  return {
    protectedPaths: [
      ".env",
      ".env.local",
      ".dekoclean",
      ".github",
      "backups",
      "package.json",
      "package-lock.json",
      "next.config.ts",
      "tsconfig.json",
      "eslint.config.mjs",
      "data",
      "app/api",
      "lib/ai-cost",
      "lib/finance",
      "lib/financial-ledger",
      "lib/participants",
      "lib/inventory",
      "lib/auth",
      "app/studio/data",
      "app/studio/engine",
      "app/studio/productMemory",
    ],
    protectedNamePatterns: [
      /(^|\/)\.env(?:\.|$)/,
      /product.?dna/i,
      /echo.?learning/i,
      /history.?store/i,
      /participant.?registry/i,
      /invoice|receipt/i,
      /uploaded.*original|original.*upload/i,
      /session|authentication|\bauth\b/i,
      /security(?:-|_)?(?:config|memory)/i,
      /(?:^|\/)manifests?(?:\/|$)/i,
    ],
    buildDirectories: [],
    cacheDirectories: [],
    dependencyDirectories: [],
    ignoredDirectories: [
      ".next", "out", "dist", "build", "coverage", "node_modules", ".git",
      ".vercel", ".cache", ".turbo", ".parcel-cache", "tmp", "temp", ".dekoclean",
    ],
    sourceExtensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".css"],
    assetExtensions: [
      ".png",
      ".jpg",
      ".jpeg",
      ".webp",
      ".gif",
      ".svg",
      ".avif",
      ".ico",
      ".mp4",
      ".webm",
      ".mov",
      ".mp3",
      ".wav",
    ],
    textExtensions: [
      ".ts",
      ".tsx",
      ".js",
      ".jsx",
      ".mjs",
      ".cjs",
      ".css",
      ".json",
      ".md",
      ".html",
      ".yml",
      ".yaml",
    ],
    dynamicReferencePatterns: [
      /import\s*\(\s*[^"'`]/,
      /require\s*\(\s*[^"']/,
      /\$\{[^}]+\}/,
      /\[(?:slug|id|category|locale|lang)\]/i,
      /glob|readdir|readFile|dynamic\s*\(/i,
    ],
    maxTextFileBytes: 2 * 1024 * 1024,
    largeLogThresholdBytes: 1024 * 1024,
    ...overrides,
    projectRoot: root,
  };
}
