import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const studio = fs.readFileSync(path.join(root, "app/studio/components/EchoImageStudio.tsx"), "utf8");
const styles = fs.readFileSync(path.join(root, "app/studio/studio.css"), "utf8");
const floatingPanel = fs.readFileSync(path.join(root, "app/studio/components/FloatingStudioPanel.tsx"), "utf8");

assert.match(studio, /useState<StudioTool>\(null\)/, "Studio must enter through an explicit idle tool state");
assert.match(studio, /activeStudioTool === null \? \(/, "idle state must replace the active workspace content");
assert.match(studio, /<h1>مرحبًا بكم في إيشوديكو ستوديو<\/h1>/, "welcome heading must remain Arabic-only");
assert.doesNotMatch(studio, /className="studio-welcome"[^>]*>[\s\S]*?EchoDeko Studio/, "welcome content must not include a Latin brand");
assert.match(studio, /aria-pressed=\{activeStudioTool === "image"\}/, "image tool must expose its pressed state");
assert.doesNotMatch(studio, /activeStudioTool === "image" && !isSmartEditOpen/, "Smart Edit launcher must not be conditionally removed in idle mode");
assert.doesNotMatch(studio, /disabled=\{!previewUrl\}/, "Smart Edit rail must stay clickable in the welcome state");
assert.match(studio, /\{windowControls\}[\s\S]*?className=\{`echoImageStudio__layout/, "window controls must be outside the workspace layout");
assert.match(studio, /className="echoImageStudio__windowControls studioWindowControls" dir="ltr"/, "window controls must use an explicit LTR wrapper");
assert.match(studio, /className="studio-main-unit">[\s\S]*?className="studio-unified-toolbar">[\s\S]*?className="studio-tab-strip"[\s\S]*?className="studio-brand-junction"[\s\S]*?className="studio-canvas-row">[\s\S]*?\{smartEditTrigger\}/, "activities, brand, canvas, and Smart Edit rail must share one connected unit");
assert.doesNotMatch(studio, /workspaceHorizontalOffset|workspaceOffsetX|studioGroupHorizontalHandle|handleWorkspaceDrag|MoveHorizontal/, "the approved Studio position must not expose workspace movement controls");
assert.match(studio, /data-activity="image" data-tooltip="معالجة الصور"[\s\S]*?aria-label="معالجة الصور"[\s\S]*?<Images/, "image activity must use one accessible custom tooltip and a specific image icon");
assert.doesNotMatch(studio, /title="(?:معالجة الصور|معالجة الفيديو[^\"]*|معالجة صور 3D[^\"]*|الليزر CNC[^\"]*|المقص الكهربائي[^\"]*|التطريز[^\"]*|اقتراح نشاط جديد)"/, "activity buttons must not duplicate custom tooltips with native titles");
assert.doesNotMatch(studio, /MainToolLabel label|studio-coming-soon|ChevronDown/, "activity buttons must contain icons without visible labels or menu chevrons");
assert.match(studio, /studio-activity-suggestion[\s\S]*?aria-label="اقتراح نشاط جديد"[\s\S]*?onClick=\{activateSuggestionTool\}[\s\S]*?<Lightbulb/, "toolbar must include an interactive activity suggestion icon");
assert.match(studio, /<Clapperboard[\s\S]*?<Cuboid[\s\S]*?<ScanLine[\s\S]*?<ScissorsLineDashed[\s\S]*?<Spool/, "each Studio activity must use a purpose-specific icon");
assert.match(studio, /data-active-activity=\{activeStudioTool \?\? "image"\}/, "Studio must expose the active activity color to Smart Edit");
assert.match(studio, /خاصية التعديل الذكي متاحة للمشاركين وفق قواعد الاستخدام المعتمدة/, "welcome must explain participant-only Smart Edit access");
assert.match(studio, /publicPath\("\/logo-dekokraft-600\.webp"\)/, "brand junction must use the base-path-safe logo helper");
assert.match(studio, /معلومات التعديل الذكي/, "brand junction must expose the Arabic Smart Edit information dialog");
assert.match(studio, /className=\{`echoVideoMainToolButton studio-tab-button[\s\S]*?disabled[\s\S]*?قريبًا/, "unavailable activities must remain visibly disabled and marked as coming soon");
assert.match(styles, /\.studio-welcome-state\s*\{/, "welcome state styling must exist");
assert.match(styles, /\.studio-tab-button\.is-active/, "explicit active tab styling must exist");
assert.match(styles, /\.studio-unified-toolbar\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0,\s*1fr\)\s+58px;/, "workspace toolbar must use explicit activities and brand columns");
assert.match(styles, /\.studioWindowControls\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?left:\s*clamp\(/, "window controls must be physically anchored to the far-left");
assert.match(styles, /@supports \(width:\s*1cqh\)[\s\S]*?\.studio-main-unit[\s\S]*?100cqh/, "the complete Studio group must be constrained by available height");
assert.doesNotMatch(styles, /studioGroupHorizontalHandle|--studio-group-offset/, "workspace movement styles must be removed");
assert.match(styles, /\.studio-smart-edit-info\s*\{[\s\S]*?right:\s*0;[\s\S]*?max-width:\s*290px;[\s\S]*?overflow-y:\s*auto;/, "logo information must stay bounded within the Studio shell");
assert.match(styles, /\.studio-tab-strip\s*\{[\s\S]*?grid-template-columns:\s*repeat\(7,\s*42px\);[\s\S]*?direction:\s*rtl;/, "tab strip must remain one seven-icon RTL row");
assert.match(styles, /\.studio-activity-item:hover::after,[\s\S]*?\.studio-activity-item:focus-visible::after,[\s\S]*?\.studio-activity-item:focus-within::after/, "activity names must appear on hover and keyboard focus");
assert.match(styles, /\.studio-activity-item\[data-activity="image"\][\s\S]*?\.studio-activity-item\[data-activity="embroidery"\]/, "activities must have distinct visual identities");
assert.match(styles, /\.studio-smart-edit-rail\s*\{[\s\S]*?var\(--active-activity-border[\s\S]*?var\(--active-activity-color/, "Smart Edit rail must inherit the active activity color");
assert.match(styles, /\.floatingStudioPanel\s*\{[\s\S]*?box-sizing:\s*border-box;/, "floating panel dimensions must include borders so clamped bounds stay inside Studio");
assert.match(floatingPanel, /const PANEL_EDGE_GAP = 12;/, "floating panels must remain at least 12px inside every Studio edge");
assert.match(floatingPanel, /const clamp = \(value: number, min: number, max: number\)/, "floating panels must use a shared numeric clamp");
assert.match(floatingPanel, /boundary\.getBoundingClientRect\(\)[\s\S]*?panel\.getBoundingClientRect\(\)/, "floating panel placement must be corrected from measured DOM dimensions");
assert.match(floatingPanel, /observer\?\.observe\(boundary\);[\s\S]*?observer\?\.observe\(panel\);/, "floating panels must re-clamp after both Studio and panel resizing");
assert.match(studio, /ref=\{floatingLayerRef\} className="echoImageStudio__floatingLayer"[\s\S]*?<FloatingImageToolPanel[\s\S]*?boundaryRef=\{floatingLayerRef\}/, "image settings must clamp against its actual positioned floating layer");
assert.match(studio, /<FloatingImageToolPanel[\s\S]*?initialAnchorRef=\{canvasRef\}/, "image settings must initially open inside the canvas upper-left corner");
assert.match(studio, /activeStudioTool === "suggestion"[\s\S]*?studio-suggestion-state[\s\S]*?إرسال الاقتراح عبر البريد الإلكتروني/, "suggestion activity must replace the canvas with Arabic email guidance");
assert.match(studio, /isOpen=\{activityPanelsVisible && \(isFiltersOpen \|\| isActionsOpen\)\}/, "image settings must hide during Smart Edit and return with activity mode");
assert.match(styles, /data-active-activity="image"\][\s\S]*?\.studio-unified-toolbar[\s\S]*?rgba\(226, 249, 239/, "image activity must use a green glass toolbar");
assert.match(styles, /data-activity="embroidery"\][\s\S]*?#a52f72/, "embroidery must retain a rose visual identity");
assert.match(styles, /\.studio-canvas-row\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0,\s*1fr\)\s+58px;/, "canvas and Smart Edit rail must use explicit columns");
assert.match(styles, /\.studio-smart-edit-rail\s*\{[\s\S]*?width:\s*58px;[\s\S]*?height:\s*100%;[\s\S]*?writing-mode:\s*vertical-rl;/, "Smart Edit must remain a connected vertical rail");
assert.match(styles, /\.studio-smart-edit-rail:disabled\s*\{[\s\S]*?opacity:\s*0\.55;/, "disabled Smart Edit rail must remain visibly present");
assert.match(studio, /useState<StudioPanelMode>\("activity"\)/, "Studio must track activity and Smart Edit panel modes explicitly");
assert.match(studio, /isOpen=\{activityPanelsVisible && \(isFiltersOpen \|\| isActionsOpen\)\}/, "activity settings must be conditionally suppressed in Smart Edit mode");

console.log("Studio idle welcome-state verification passed.");
