import {updateKnowledgeTree} from "./knowledgeTree";import {createOrUpdateProductDNA,evolveProductDNA,replaceProductDNA} from "./productDna";import {loadLearningState,saveLearningState} from "./storage";import type {DekoBrainLearningState,EchoLearningEvent,LearningContext,LearningSource,ProductCategory} from "./types";
const points:Record<LearningSource,number>={localAnalysis:0,userCorrection:3,userConfirmation:2,appliedRecommendation:1,identityMatch:1};
function stableEventId(context:LearningContext,source:LearningSource,resultApproved:boolean){const stamp=new Date().toISOString(),unique=typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`${stamp}-${context.mediaFingerprint}-${source}`;return{stamp,id:`${context.mediaFingerprint}:${resultApproved?"approved":"pending"}:${unique}`}}
function record(context:LearningContext,source:LearningSource,input:{confirmed?:boolean;approved?:boolean;reason:"created"|"categoryCorrected"|"categoryConfirmed"|"recommendationApplied"|"resultApproved";points?:number}){let state=loadLearningState();const base=createOrUpdateProductDNA(state,context);if(!state.productDna.some(item=>item.mediaFingerprint===context.mediaFingerprint))state=replaceProductDNA(state,base);const duplicate=state.events.find(event=>event.mediaFingerprint===context.mediaFingerprint&&event.source===source&&event.correctedCategory===context.category&&event.resultApproved===Boolean(input.approved)&&event.userConfirmedCategory===Boolean(input.confirmed)&&(source!=="appliedRecommendation"||JSON.stringify(event.settings)===JSON.stringify(context.settings)));if(duplicate)return{state,dna:base,event:duplicate};const score=input.points??points[source],{stamp,id}=stableEventId(context,source,Boolean(input.approved));const event:EchoLearningEvent={id,mediaFingerprint:context.mediaFingerprint,timestamp:stamp,predictedCategory:context.predictedCategory,correctedCategory:context.category,predictionConfidence:context.confidence,userConfirmedCategory:Boolean(input.confirmed),source,sceneComplexity:context.sceneComplexity,riskLevel:context.riskLevel,protectedFeatures:context.protectedFeatures,settings:context.settings,resultApproved:Boolean(input.approved)};const evolved=evolveProductDNA(base,context,{reason:input.reason,points:score,confirmed:input.confirmed,approved:input.approved});state=replaceProductDNA({...state,events:[...state.events,event]},evolved);state=updateKnowledgeTree(state,event,score);return{state:saveLearningState(state),dna:evolved,event}}
export const recordCategoryCorrection=(context:LearningContext)=>record(context,"userCorrection",{reason:"categoryCorrected"});
export const recordCategoryConfirmation=(context:LearningContext)=>record(context,"userConfirmation",{reason:"categoryConfirmed",confirmed:true});
export const recordRecommendationApplied=(context:LearningContext)=>record(context,"appliedRecommendation",{reason:"recommendationApplied"});
export const recordResultApproval=(context:LearningContext)=>record(context,"userConfirmation",{reason:"resultApproved",approved:true,points:4});
export const recordIdentityMatch=(context:LearningContext)=>record(context,"identityMatch",{reason:"categoryConfirmed",confirmed:true,points:1});
export function getEchoScoreForCategory(category:ProductCategory,state: DekoBrainLearningState=loadLearningState()){return state.knowledgeTree[category]?.echoScore??0}
export function getLearningSummary(state:DekoBrainLearningState=loadLearningState()){return{schemaVersion:state.schemaVersion,eventCount:state.events.length,dnaCount:state.productDna.length,categoryCount:Object.keys(state.knowledgeTree).length,totalEchoScore:Object.values(state.knowledgeTree).reduce((sum,item)=>sum+(item?.echoScore??0),0),lastEvent:state.events.at(-1)??null}}
