import {createEmptyLearningState,createMediaFingerprint,createOrUpdateProductDNA,getLearningSummary,normalizeProductCategory,recordCategoryConfirmation,recordCategoryCorrection,recordRecommendationApplied,recordResultApproval,replaceProductDNA,saveLearningState,type LearningContext} from "./index";
function assert(condition:boolean,message:string){if(!condition)throw new Error(message)}
const values=new Map<string,string>();const localStorage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)},removeItem:(key:string)=>{values.delete(key)},clear:()=>values.clear(),key:(index:number)=>[...values.keys()][index]??null,get length(){return values.size}};
Object.defineProperty(globalThis,"window",{value:{localStorage},configurable:true});Object.defineProperty(globalThis,"localStorage",{value:localStorage,configurable:true});
const metadata={name:"pink-candle.jpg",size:2048,type:"image/jpeg",lastModified:123,width:800,height:1200};const fingerprint=createMediaFingerprint(metadata);assert(fingerprint===createMediaFingerprint(metadata),"stable fingerprint");assert(fingerprint!==createMediaFingerprint({...metadata,size:2049}),"metadata-sensitive fingerprint");assert(normalizeProductCategory("شموع")==="candle"&&normalizeProductCategory("other")==="unknown","category normalization");
const base:LearningContext={mediaFingerprint:fingerprint,predictedCategory:"unknown",category:"unknown",confidence:28,sceneComplexity:"simple",riskLevel:"high",sourceType:"uploaded",protectedFeatures:[],settings:{backgroundSensitivity:45,edgeSoftness:25,detailProtection:88,shadowMode:"keep"}};let state=createEmptyLearningState();state=replaceProductDNA(state,createOrUpdateProductDNA(state,base));saveLearningState(state);
const corrected=recordCategoryCorrection({...base,category:"candle",riskLevel:"medium",protectedFeatures:["flame","wick","shadow","fineEdges","fineDetails"]});assert(corrected.dna.version===2&&corrected.dna.echoScore===3,"correction evolves DNA");
const confirmed=recordCategoryConfirmation({...base,category:"candle",riskLevel:"medium",protectedFeatures:corrected.dna.protectedFeatures});assert(confirmed.dna.echoScore===5&&confirmed.dna.userConfirmedCategory,"confirmation score");
const applied=recordRecommendationApplied({...base,category:"candle",riskLevel:"medium",protectedFeatures:corrected.dna.protectedFeatures,settings:{backgroundSensitivity:62,edgeSoftness:22,detailProtection:90,shadowMode:"keep"}});assert(applied.dna.echoScore===6&&applied.dna.preferredSettings.detailProtection===90,"recommendation score and settings");
const approved=recordResultApproval({...base,category:"candle",riskLevel:"medium",protectedFeatures:corrected.dna.protectedFeatures,settings:applied.dna.preferredSettings});const summary=getLearningSummary(approved.state);assert(approved.dna.echoScore===10&&approved.dna.resultApproved,"approval score");assert(summary.eventCount===4&&summary.totalEchoScore===10,"learning summary");
