import type {DekoBrainLearningState,DnaHistoryReason,LearningContext,ProductDNA} from "./types";
import {silhouetteMeaningfullyChanged,type SilhouetteDnaResult} from "../silhouetteDna";
const clamp=(value:number)=>Math.max(0,Math.min(100,value));
export function calculateDnaConfidence(base:number,dna:Pick<ProductDNA,"echoScore"|"userConfirmedCategory"|"resultApproved"|"sceneComplexity">,risk:"low"|"medium"|"high"){return clamp(base+(dna.userConfirmedCategory?8:0)+(dna.resultApproved?7:0)+Math.min(10,dna.echoScore*.5)-(dna.sceneComplexity==="complex"?12:dna.sceneComplexity==="medium"?4:0)-(risk==="high"?10:risk==="medium"?3:0))}
export function getProductDNA(state:DekoBrainLearningState,fingerprint:string){return state.productDna.find(item=>item.mediaFingerprint===fingerprint)??null}
export function getDnaVersionLabel(dna:Pick<ProductDNA,"version">){return`v${dna.version}`}
export function createOrUpdateProductDNA(state:DekoBrainLearningState,context:LearningContext):ProductDNA{const existing=getProductDNA(state,context.mediaFingerprint);if(existing)return existing;const now=new Date().toISOString();return{id:`dna-${context.mediaFingerprint}`,mediaFingerprint:context.mediaFingerprint,version:1,category:context.category,confidence:context.confidence,echoScore:0,sceneComplexity:context.sceneComplexity,sourceType:context.sourceType,protectedFeatures:context.protectedFeatures,preferredSettings:context.settings,userConfirmedCategory:false,resultApproved:false,createdAt:now,updatedAt:now,history:[{version:1,timestamp:now,reason:"created",echoScore:0}]}}
export function evolveProductDNA(dna:ProductDNA,context:LearningContext,input:{reason:DnaHistoryReason;points:number;confirmed?:boolean;approved?:boolean;forceVersion?:boolean}){const categoryChanged=dna.category!==context.category,confirmationChanged=Boolean(input.confirmed)&&!dna.userConfirmedCategory,approvalChanged=Boolean(input.approved)&&!dna.resultApproved,settingsChanged=JSON.stringify(dna.preferredSettings)!==JSON.stringify(context.settings);const changed=input.forceVersion||categoryChanged||confirmationChanged||approvalChanged||(input.reason==="recommendationApplied"&&settingsChanged);const version=dna.version+(changed?1:0),echoScore=dna.echoScore+input.points,now=new Date().toISOString();const next={...dna,version,category:context.category,echoScore,sceneComplexity:context.sceneComplexity,sourceType:context.sourceType,protectedFeatures:context.protectedFeatures,preferredSettings:context.settings,userConfirmedCategory:dna.userConfirmedCategory||Boolean(input.confirmed),resultApproved:dna.resultApproved||Boolean(input.approved),updatedAt:now};next.confidence=calculateDnaConfidence(context.confidence,next,context.riskLevel);if(changed)next.history=[...dna.history,{version,timestamp:now,reason:input.reason,previousCategory:categoryChanged?dna.category:undefined,newCategory:categoryChanged?context.category:undefined,echoScore}];return next}
export function replaceProductDNA(state:DekoBrainLearningState,dna:ProductDNA){return{...state,productDna:[...state.productDna.filter(item=>item.mediaFingerprint!==dna.mediaFingerprint),dna]}}
export function updateProductDnaSilhouette(dna:ProductDNA,silhouetteDna:SilhouetteDnaResult,input:{shapeCorrected?:boolean;colorVariant?:boolean;sizeVariant?:boolean;decorationVariant?:boolean}={}){const changed=silhouetteMeaningfullyChanged(dna.silhouetteDna,silhouetteDna),version=dna.version+(changed?1:0),timestamp=new Date().toISOString();return{...dna,version,silhouetteDna,shapeCorrections:(dna.shapeCorrections??0)+(input.shapeCorrected?1:0),colorVariantsSeen:(dna.colorVariantsSeen??0)+(input.colorVariant?1:0),sizeVariantsSeen:(dna.sizeVariantsSeen??0)+(input.sizeVariant?1:0),decorationVariantsSeen:(dna.decorationVariantsSeen??0)+(input.decorationVariant?1:0),updatedAt:changed?timestamp:dna.updatedAt,history:changed?[...dna.history,{version,timestamp,reason:"silhouetteUpdated" as const,echoScore:dna.echoScore}]:dna.history}}
