import type {DekoBrainLearningState} from "./types";
export const LEARNING_STORAGE_KEY="dekokraft.dekobrain.learning.v1";const MAX_EVENTS=500;
export const createEmptyLearningState=():DekoBrainLearningState=>({schemaVersion:1,events:[],productDna:[],knowledgeTree:{}});
function isState(value:unknown):value is DekoBrainLearningState{if(!value||typeof value!=="object")return false;const state=value as Partial<DekoBrainLearningState>;return state.schemaVersion===1&&Array.isArray(state.events)&&Array.isArray(state.productDna)&&Boolean(state.knowledgeTree)&&typeof state.knowledgeTree==="object"}
export function loadLearningState(){if(typeof window==="undefined")return createEmptyLearningState();try{const parsed:unknown=JSON.parse(localStorage.getItem(LEARNING_STORAGE_KEY)??"null");return isState(parsed)?{...parsed,events:parsed.events.slice(-MAX_EVENTS)}:createEmptyLearningState()}catch{return createEmptyLearningState()}}
export function saveLearningState(state:DekoBrainLearningState){const safe:{schemaVersion:1;events:DekoBrainLearningState["events"];productDna:DekoBrainLearningState["productDna"];knowledgeTree:DekoBrainLearningState["knowledgeTree"]}={schemaVersion:1,events:state.events.slice(-MAX_EVENTS),productDna:state.productDna,knowledgeTree:state.knowledgeTree};if(typeof window!=="undefined")try{localStorage.setItem(LEARNING_STORAGE_KEY,JSON.stringify(safe))}catch{}return safe}
export function resetLearningState(){const empty=createEmptyLearningState();if(typeof window!=="undefined")try{localStorage.removeItem(LEARNING_STORAGE_KEY)}catch{}return empty}
export function exportLearningState(){return JSON.stringify(loadLearningState(),null,2)}
export function importLearningState(json:string){const parsed:unknown=JSON.parse(json);if(!isState(parsed))throw new Error("invalid-learning-state");return saveLearningState({...parsed,events:parsed.events.slice(-MAX_EVENTS)})}
export function createMediaFingerprint(metadata:{name:string;size:number;type:string;lastModified:number;width:number;height:number}){const value=[metadata.name.trim().toLowerCase(),metadata.size,metadata.type,metadata.lastModified,metadata.width,metadata.height].join("|");let hash=2166136261;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return`media-${(hash>>>0).toString(16).padStart(8,"0")}-${value.length.toString(16)}`}
